### ISSUE TITLE
Publish manylinux2014 wheels

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [psycopg/psycopg#124]
Hi Daniele, thanks so much for your hard work on this! Glad to see it out of beta! I work for a company that's still on CentOS 7 (and will be for a while) which means that we can't currently install any of the wheels from PyPI because they're all manylinux_2_24 (we're on libc 2.17). Would you consider publishing manylinux2014 wheels as well?

**Comment by rafmagns-skepa-dreag** [comment]
Sorry to disappear for a month. Been traveling and working on other things. I see that psycopg includes a far more comprehensive matrix for wheels than psycopg2. Would you rather I limit the manylinux2014 build to x86 and i686 or add it as another item in the matrix which will push the number of linux wheels from 40 up to 80. I'm testing out the image right now to make sure the build works as expected

**Comment by dvarrazzo** [comment]
Hello Richard, and thank you very much, no need to apologise.

> limit the manylinux2014 build to x86 and i686

This would be better, yes: a psycopg release is already in the order of 150Mb on PyPI.

Could you please let me know, in the Centos image used for the build:
- what libpq library is available? Ideally it should have 14.1, the important is that it has one of the versions [not affected by CVE-2021-23222](https://www.postgresql.org/about/news/postgresql-141-135-129-1114-1019-and-9624-released-2349/) (14.1, 13.5, 12.9, 11.14, 10.19, and 9.6.24). If not, we need to compile the libpq from source.
- what openssl library is available on the system? 1.1.x or 1.0.x? 1.0 has been long untested and has concurrency problems that have affected psycopg2 for long time. I don't think people had problems with 1.1.x. This should be built from source too if not available.
- There is a `build_libpq.sh` script in psycopg2 `scripts/build` directory which you are free to use and should probably work mostly out-of-the-box.
- If possible, it would be amazing if you could also fix the sysconfdir in order to solve https://github.com/psycopg/psycopg2/issues/1365 - I assume it's `./configure --sysconfdir=/etc/postgresql-common` at libpq configure time. Or, probably, the value used for Centos would be more appropriate... What does `pg_config --sysconfdir` tells you on Centos?

Cheers!

**Comment by rafmagns-skepa-dreag** [comment]
Looks like we'll have to build openssl (1.0.2 installed) and libpq (none installed, 5.5 available from postgres 9.2.24 in the default repositories). I'll check out the sysconfig stuff though I'm not confident about getting a real answer. 

Also, I said x86_64 and i686 but meant aarch64 instead of i686. I imagine all the new mac owners will want wheels.

**Comment by dvarrazzo** [comment]
9.2 is too old to be serviceable. It will require `build_libpq.sh`.  That extends painfully the wheels build time though: if it was possible to cache the result artifacts it would be great. Psycopg 2 does it on appveyor but not on github actions; I don't know if there is any service we can leverage on github.

**Comment by dvarrazzo** [comment]
Hi,

just to let you know, after knowing of https://github.com/pypa/manylinux/issues/1332 I think we should bite the bullet and publish manylinux2014 wheels. I will dust off the psycopg2 build script and adapt it to psycopg 3.

**Comment by rafmagns-skepa-dreag** [comment]
thank you so much! I'm sorry I wasn't able to help here. I really appreciate your work on this - I know how tedious it is to wait for these long build times

**Comment by dvarrazzo** [comment]
Psycopg 3.0.15 released with manylinux2014 support. Please let me know if it works well for you :)

**Comment by rafmagns-skepa-dreag** [comment]
I'll be trying it out later today but it installed just fine. Thanks!
