### ISSUE TITLE
Connection exception sent to logger instead of being raised

### ISSUE THREAD

**Issue by fabiog1901** [psycopg/psycopg#189]
Ciao Daniele,

this is a bit more of a question/observation/request-for-advice rather than an actual 'bug', I'm not qualified enough to claim that status for what I'm raising here.

In file [connection.py](https://github.com/psycopg/psycopg/blob/master/psycopg/psycopg/connection.py#L689&L694), in method `__exit__()` of class `Connection`, I had to change this snippet of code from

```python
            except Exception as exc2:
                logger.warning(
                    "error ignored in rollback on %s: %s",
                    self,
                    exc2,
                )
```

to 

```python
            except Exception as exc2:
                # logger.warning(
                #     "error ignored in rollback on %s: %s",
                #     self,
                #     exc2,
                # )
                # ValueError is just because it's simple to catch
                raise ValueError(exc2)
```

to be able to catch that Exception on my main Process when I interrupt (Ctrl+C) and avoid otherwise printing the large stacktrace from the many processes that have opened a connection.

The Main-Process uses multiprocessing to create several processes. Each process opens a connection to the db and, in an infinite loop, transactions are executed. When Ctrl+C is sent, Main-Process stops each process, but these often throw the WARNING log message, which I can't seem to avoid. So by raising the Exception as a simple ValueError instead of printing it to log, in Main-Process I'm able to catch the ValueError and silently ignore it. Here, ValueError is just a quick-and-dirty fix, by no means a suggestion on how it should be resolved.

Looking forward to your thoughts on this. 

Thank you
Fabio

**Comment by dvarrazzo** [comment]
Ciao Fabio,

I assume, to the same intent, you can replace the logging with just `pass`, right? As you are in the exit method, python will raise the original exception (instead of the exception raised by the failed rollback) which is up to you to ignore, as you do with your ValueError.

The logger is configurable: you can use `logging.getLogger("psycopg").setLevel(logging.ERROR)` to silence it.

In that bit of code we are in the uncomfortable position of a possible exception being raised while an exception is handled. Because we consider the original exception more important, we don't let the second one clobber it. If you have different ideas about how to do it, we'd be happy to know.

Maybe you could also consider to organise your program in a different way to avoid a brutal disconnection, e.g. with queues?

**Comment by fabiog1901** [comment]
Thank you Daniele,

Yes, `pass` would do the trick too, and in a simpler way, but I really want to avoid touching the libraries if I can avoid it!
Indeed, the right solution is to gracefully stop the connections instead of abruptly kill the process that runs it - thanks for the guidance, I'll work on that next. For the time being, setting the logger to just output ERRORs works very well. 

I appreciate the assistance as always.

Best,
Fabio

**Comment by dvarrazzo** [comment]
> but I really want to avoid touching the libraries if I can avoid it!

Sure, I was just wondering if there wasn't any unexpected factor for which raising the exception was doing something else. The right thing to do, according to the library design, is to configure the logger to ignore the warning, and it's something you can do from your program of course.

Thank you for testing!
