### ISSUE TITLE
Use Python development in tests?

### ISSUE THREAD

**Issue by adamchainz** [psycopg/psycopg#202]
Have you used [Python's development mode](https://docs.python.org/3/library/devmode.html) in tests? It could be useful on CI to guarantee no memory allocation problems etc.

I'm just asking because psycopg is a prominent C extension and I'm wondering how much value development mode provides to C extension development.

**Comment by dvarrazzo** [comment]
Hi @adamchainz 

Thank you for the heads up. I just tried running both psycopg2 and 3 test suites with that flag and they reported no errors or warnings.

Actually, testing better, in psycopg there is no problem with the quick tests. Trying the complete tests, it seems that `-X dev` causes a false positive. Several tests fail reporting an object leak across runs (that's our test, not a check in `-X dev`. Unfortunately it's not easy to reproduce, so something fails when using `python -X dev -m pytest --lf -x` but doesn't when run singularly.

Other tests seem to fail either because of extra warnings generated (of the type `Executing <Task pending ...> took 0.218 seconds`) or maybe because of timing changes. For instance this fails regularly, and not surprisingly it tests that certain log messages are generated:

```
$ python -X dev -m pytest --lf -x tests/pool/test_pool_async.py::test_reconnect
```

So it is an interesting one-off experiment, but I'm not comfortable in dropping it in the test suite...

**Comment by adamchainz** [comment]
Thanks, good to know. I tried adding devmode to all my projects and it's working fine, but they aren't as low level as psycopg.
