### ISSUE TITLE
psycopg_pool: BasePool takes `kwargs` instead of `**kwargs`

### ISSUE THREAD

**Issue by loovjo** [psycopg/psycopg#341]
Hi! It seems like the `BasePool` class takes an argument named `kwargs`, instead of being specified as `**kwargs`, meaning one has to write i.e.
```py
pgpool.AsyncConnectionPool(conninfo, kwargs={"password": PASSWORD})
```
instead of the intended
```py
pgpool.AsyncConnectionPool(conninfo, password=PASSWORD)
```

While defined here,
https://github.com/psycopg/psycopg/blob/71b989f92aec00a54b9b4c5a7c4ed3d4d9c457ab/psycopg3/psycopg3/pool/base.py#L33

it seems `kwargs` instead of `**kwargs` was already used in the `ConnectionPool` class from the commit before. It seems like the commit https://github.com/psycopg/psycopg/commit/9a45d010cccd225c0454a02d539f0d69a4ca5efd introduced the issue.

While this is in no way critical, and a workaround presented above works, it's should be a very simple issue to fix.

**Comment by dvarrazzo** [comment]
That's correct, `kwargs` on the pool is a single variable and it's a design choice. It is also [documented here](https://www.psycopg.org/psycopg3/docs/api/pool.html#the-connectionpool-class).

Connections support an open-ended set of parameters, because they are [whatever Postgres accepts](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS). The pool supports a huge number of parameters, about 15. There is a high risk of collision between the two sets of parameters. Keeping the connection kwargs into a single pool argument makes the things more manageable.
