### ISSUE TITLE
asyncio connect blocks event loop by running synchronous connect code 

### ISSUE THREAD

**Issue by WoLpH** [psycopg/psycopg#342]
When using psycopg in asyncio mode I've noticed these warnings at times:
```
WARNING Executing <Task pending name='pool-1-worker-0' coro=<AsyncConnectionPool.worker() running at db.py:150> took 0.115 seconds
```

After a little search through the code I've been able to narrow it down to the `wait_conn_async` function: https://github.com/psycopg/psycopg/blob/47019949990c5ea2007096a84d844722796212c8/psycopg/psycopg/waiting.py#L152-L206
Specifically line 178, the waiting for the connection generator:
https://github.com/psycopg/psycopg/blob/47019949990c5ea2007096a84d844722796212c8/psycopg/psycopg/waiting.py#L178

Looking slightly further it seems that internally this synchronous code is being called which is the cause of this issue: https://github.com/psycopg/psycopg/blob/47019949990c5ea2007096a84d844722796212c8/psycopg/psycopg/connection.py#L430-L441

Because it's a coroutine itself, we cannot simply execute the `next(gen)` section in a `asyncio` background task. But it would be nice if we wouldn't block the event loop while waiting for a connection :)

**Comment by dvarrazzo** [comment]
Hi, thank you for your report.

The generator should be non blocking, but it might still block for reasons explained [here](https://www.postgresql.org/docs/current/libpq-connect.html) (see `PQconnectStart`), usuay caused by DNS name resolution.

There is [a workaround](https://www.psycopg.org/psycopg3/docs/advanced/async.html) in psycopg 3.0, and async name resolution is implemented by default (#259) in 3.1 (due to release in a few days).

What is the connection string/env vars you are using?

**Comment by WoLpH** [comment]
Hi,

DNS resolution must be the issue in that case... thank you for the quick response! I guess this request is moot now :)

**Comment by dvarrazzo** [comment]
Cool, I'm glad it's a known problem and not a new one! 😄

Did you solve it by using [resolve_hostaddr_async()](https://www.psycopg.org/psycopg3/docs/api/dns.html#psycopg._dns.resolve_hostaddr_async)?

**Comment by WoLpH** [comment]
I went for the simpler solution, using the IP address. It's fixed anyhow in this case :)
