### ISSUE TITLE
Async django: I need your review

### ISSUE THREAD

**Issue by pwtail** [psycopg/psycopg#369]
Hi @dvarrazzo 

I'm sorry I opened an issue, I promise not to ever do it again for this purpose. You may close it if you wish.

I've been experimenting with how I can produce an async version of django and ended with both sync an async versions.

Here it is: https://github.com/vinylproject/vinyl

Would like to know what you think about it. For the start, it provides natively sync and async versions, which no other orm is doing. (And is using psycopg of course!) Also it takes interesting approach for writing the universal sync/async code: you write just the async version and then apply the static transform.

If you notice some general blunders or things you disagree in principle - that would be very useful for me. As the library is kinda going past the proof-of-concept stage

**Comment by dvarrazzo** [comment]
Hello @pwtail,

I took a quick look, left a few notes, but I just skimmed the surface.

Your project has pretty much no comment, so it's difficult to understand what goes on there. Even the git commit messages give no info. It also has no test at all, which is not a good sign. I understand this is a proof-of-concept, but I still believe you need tests to show how the system would behave altogether and how code using your library would be written.

I understand it is a wrapper around the django backend, which makes it harder for me to understand, because you need some knowledge of that system. I only know it as a user, I have rarely looked under the hood. I mostly looked at the psycopg code because I might be able to see if something is clearly wrong, but you can't expect me to review descriptors and querysets. What I can tell is: there are no tests, therefore I have no proof that it even works.

"I will add the tests later" will not happen :smile: 

I haven't seen the static transform to make the async code sync. It could be interesting to take a look at, but I assume it will take a huge performance hit. Async code is inherently slower compared to sync code, because it is based on generators and exceptions.

All in all, I'm happy if django moves towards enabling an async database layer too, so good luck with your project!

**Comment by pwtail** [comment]
Thank you for the review. Special thanks for the issues! It's true the codebase has no comments. The important points are
1. sync version is autogenerated (transpiled) from the async one. Much like you get javascript code from typescript.
2. the entire rewrite is incapsulated in a model manager. This approach can also help bring whatever incompatible changes to django project itself.
3. The db backends. For example, the sync version uses psycopg_pool with size=1 

What relates to testing, the interesting part is that I can reuse the most part of the django testsuite for vinyl_sync. And I expect this to find a lot of bugs. But will add the smoke tests too, for both versions.
