### ISSUE TITLE
`INSERT ... RETURNING *` only giving one row

### ISSUE THREAD

**Issue by bflanders** [psycopg/psycopg#468]
I am trying to take advantage of postrges `insert ... returning *` idiom. The cursor for psycopg doesn't like to return all the rows.

Here is my code:
```
import psycopg as db

# I build a connection utility
conn = db.connect(pg_config(conf))
create_sql = '''
    create table foo (key text, value integer)
'''

insert_sql = '''
    insert into foo values (%s, %s)
    returning *
'''

with conn.cursor() as cur:
    data = [('a', 1), ('b', 2)]
    cur.executemany(insert_sql, data, returning=True)
    conn.commit()
    for row in cur.fetchall():
        print(row)
conn.close()

# >>> ('a', 1)
```
Python version: 3.10.8
psycopg: 3.1.7

**Comment by dvarrazzo** [comment]
As [per docs](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.executemany), you must use nextset() to get the results of the following queries.

**Comment by bflanders** [comment]
Changed the last block to be:

```
with conn.cursor() as cur:
    data = [('a', 1), ('b', 2)]
    cur.executemany(insert_sql, data, returning=True)
    conn.commit()
    print(cur.fetchone())
    while cur.nextset():
        print(cur.fetchone())
conn.close()
```

That worked. Seems a little clunky that `cur.fetchall`, but that's me. 

Thanks for the quick feedback.

**Comment by dvarrazzo** [comment]
> Seems a little clunky that `cur.fetchall`, but that's me.

I know, but we need to differentiate iterating on the rows returned by a single INSERT from iterating on the results of the different statements. In your case, you know that each INSERT returns only one row, but executemany might be used to execute several queries, each one returning several rows.

Using `nextset()` is equivalent (but faster) of executing a sequence of queries:

```python
cur.execute("""
    insert into ... values ('a', 1) returning *;
    insert into ... values ('b', 2) returning *;
""")

and then reading each statement's results. psycopg2 only makes the last one available; Psycopg 3 gives access to all of them, and the user can iterate on each result (as opposite as iterating on the rows of a single result) using `nextset()` as well.

**Comment by bflanders** [comment]
Ah. Makes sense. Thanks again!

**Comment by bluenote10** [comment]
I was running into that issue as well. Perhaps the docs could be improved a little bit. I was reading them, but the way they were phrased made me think the opposite of what they are trying to express. In particular these two sentences:

> the results will be available in the cursor’s state and can be read using fetchone() and similar methods.

This sentence suggested to me that `fetchall` should give me all results.

> Each input parameter will produce a separate result set: use nextset() to read the results of the queries after the first one.

I failed to understand that sentence, because it was unclear to me what "parameter" refers to. I thought, "parameter" refers to columns. So if multiple columns have a `RETURNING` value I need to use `nextset()` to switch to the next one, and for each one I would either use `fetchone`/`fetchmany`/`fetchall` to get either one or many values for that column.

From a user perspective `executemany` is just one query. That makes the perspective _you must use nextset() to get the results of the following queries_ a bit confusing, because the user doesn't know that there are multiple queries under the hood (I assume?).

What I don't understand yet is: What is the difference between `fetchone`/`fetchmany`/`fetchall` in that context? They all seem to behave the same. Perhaps explaining that in the docs could help. Or perhaps it could help to document that pattern if it is kind of a standard for `executemany` with `RETURNING`:

```py
collected_results = [cur.fetchone()]
while cur.nextset():
    collected_results.append(cur.fetchone())
```

(Feels a bit clumsy, am I missing a more elegant pattern?)

**Comment by dvarrazzo** [comment]
@bluenote10 thank you for the feedback, very appreciated.

A single query execution in executemany (i.e. the input query executed with one of the parameters items in the input sequence) can possibly return more than one record. A silly example:

```python
>>> cur.executemany("select generate_series(1, %s)", [(2,), (3,), (1,)], returning=True)

>>> cur.fetchall()
[(1,), (2,)]

>>> cur.nextset()
True

>>> cur.fetchall()
[(1,), (2,), (3,)]

>>> cur.nextset()
True

>>> cur.fetchall()
[(1,)]

>>> cur.nextset()
```

In this case, `fetchone()` would return (1,), then (2,), then None, and using `nextset()` you would move on the next result set of 3 records. The case of `insert into ... values ()... returning *`, returning a single record, is the common case, I agree, for which it's confusing the reason why fetchone/nextset are required.

With this extra bit of knowledge, would you be able to suggest a wording for the documentation, which might explain better to a newcomer the behaviour of the method?

Thank you very much :)

**Comment by bluenote10** [comment]
Thanks for the clarification! In fact, the example is pretty spot on to illustrate how it all works, so maybe just use that in the documentation? It could be followed-up by something addressing the standard use case:

_In the most common use case of using `RETURNING`, only a single record is returned per input record to `executemany`. In this case there is no difference between using `fetchone`/`fetchmany`/`fetchall`. Collecting all returned records in this case requires to use a pattern like this:_

... and then the snippet with `collected_results` from above, or so?

**Comment by dvarrazzo** [comment]
> In this case there is no difference between using fetchone/fetchmany/fetchall

Note: there is a difference if your RETURNING id is guaranteed to return only one record: fetchone() would return (1,), fetchmany() and fetchall() would return [(1,)]. So, most likely, most people will want fetchone() in the loop :upside_down_face: 

Let's wordsmith something:

---

If the queries return data you want to read (e.g. when executing an `INSERT ... RETURNING` or a `SELECT` with a side-effect), you can specify `returning=True`. This is equivalent of calling `execute()` as many times as the number of items in `params_seq` and to store all the results in the cursor's state.

Using the usual `fetch*()` you will be able to read the records returned *by the first query executed*. In order to read the results of the following queries you can call `nextset()` to move to the following result set.

A typical case is to execute a query such as `INSERT INTO table VALUES (...) RETURNING id` in order to insert a bunch of records and retrieve the list of ids of the records inserted. In such case, you can use a pattern such as:

```python
cur.executemany(query, records)
ids = [cur.fetchone()[0]]
while cur.nextset():
    ids.append(cur.fetchone()[0])
```        

---

This explains several things:

- all the state is in the cursor: careful with the memory.
- several query are executed: one for each params set (true also in the non-returning case anyway)
- we have an example for the most common use case (thank you for it).

What do you think?

**Comment by dvarrazzo** [comment]
Maybe a better wording for the last paragraph:

---

A typical use case is to execute a query such as `INSERT INTO table VALUES (...) RETURNING id`, in order to insert a bunch of records and to retrieve the ids of the records inserted. In such case, every query is guaranteed to insert a single record and will return a single value. As a consequence, in order to obtain a list of the ids inserted, you can use a pattern such as:

**Comment by dvarrazzo** [comment]
I added [some documentation](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.executemany) about the issues you faced. Feedback is welcome, thank you very much

**Comment by bflanders** [comment]
I like it! Well said.
