### ISSUE TITLE
Using a prerelease version of cython is problematic for distribution packaging

### ISSUE THREAD

**Issue by dvzrv** [psycopg/psycopg#471]
Hi! I'm currently working on removing the use of pip from our packaging process on Arch Linux (as it allows packages to download arbitrary dependencies from unknown locations and execute them).

I noticed that psycopg makes use of a prerelease version of cython (3.0.0a11):

```
/usr/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
/usr/bin/python: No module named pip
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp63nki98q', '--quiet', 'Cython>=3.0.0a11']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/build/python-psycopg/src/python-psycopg/psycopg_c/setup.py", line 106, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
    return installer(requirement)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp63nki98q', '--quiet', 'Cython>=3.0.0a11']' returned non-zero exit status 1.
```

This effectively means that downstream distributions would install cython in an arbitrary version >= 3.0.0a11 in their packaging environments, which means the downloading of a package without version pinning in the context of the build system, leading to unreproducible packages.

Since cython 3.0.0 is not released in a stable version, it is also not packaged on downstream distributions (apart from some bizarre edge cases): https://repology.org/project/python:cython/versions
Therefore the optimized version of psycopg can not be packaged cleanly (and reproducibly).

Can you please make the build compatible with the current stable version of cython?

**Comment by dvarrazzo** [comment]
Hello,

no, it's impossible. "Stable" Cython is years behind and missing features.

However, please note that the `psycopg-c` package doesn't depend on Cython. This is the content of the package:

```
curl -sSL https://files.pythonhosted.org/packages/df/0e/11159cbdffb260bc79ab46fe33e36083506f1204ba5ef7686b45df5d03da/psycopg-c-3.1.7.tar.gz | tar tzf -
psycopg-c-3.1.7/
psycopg-c-3.1.7/LICENSE.txt
psycopg-c-3.1.7/PKG-INFO
psycopg-c-3.1.7/README.rst
psycopg-c-3.1.7/psycopg_c/
psycopg-c-3.1.7/psycopg_c/__init__.py
psycopg-c-3.1.7/psycopg_c/_psycopg/
psycopg-c-3.1.7/psycopg_c/_psycopg/__init__.pxd
psycopg-c-3.1.7/psycopg_c/_psycopg/endian.pxd
psycopg-c-3.1.7/psycopg_c/_psycopg/oids.pxd
psycopg-c-3.1.7/psycopg_c/_psycopg.c
psycopg-c-3.1.7/psycopg_c/_psycopg.pyi
psycopg-c-3.1.7/psycopg_c/pq/
psycopg-c-3.1.7/psycopg_c/pq/__init__.pxd
psycopg-c-3.1.7/psycopg_c/pq/libpq.pxd
psycopg-c-3.1.7/psycopg_c/pq.c
psycopg-c-3.1.7/psycopg_c/pq.pxd
psycopg-c-3.1.7/psycopg_c/py.typed
psycopg-c-3.1.7/psycopg_c/types/
psycopg-c-3.1.7/psycopg_c/types/numutils.c
psycopg-c-3.1.7/psycopg_c/version.py
psycopg-c-3.1.7/psycopg_c.egg-info/
psycopg-c-3.1.7/psycopg_c.egg-info/PKG-INFO
psycopg-c-3.1.7/psycopg_c.egg-info/SOURCES.txt
psycopg-c-3.1.7/psycopg_c.egg-info/dependency_links.txt
psycopg-c-3.1.7/psycopg_c.egg-info/not-zip-safe
psycopg-c-3.1.7/psycopg_c.egg-info/top_level.txt
psycopg-c-3.1.7/pyproject.toml
psycopg-c-3.1.7/setup.cfg
psycopg-c-3.1.7/setup.py
```

you can see it contains metadata, headers (the `.pxd` files) and C files (`pq.c` and `_psycopg.c`) which are the result of compiling the Cython files to C. This package is actually designed to be installed without Cython and doesn't contain Cython code.

What could be is the build-system/requires in `pyproject.toml` to be incorrect in requiring Cython. In the past this wasn't a problem because `python setup.py build` wouldn't have installed it, and the `setup.py` is specifically designed to not require it if there is no Cython file to compile:

https://github.com/psycopg/psycopg/blob/1434fd42141214f6bfe73bf388bad8feb6bed672/psycopg_c/setup.py#L39-L74

If I understand correctly, the Python build system is starting to take in consideration the build tools in cases that weren't previously required. See also pypa/setuptools/issues/3734
for an issue that I have reported caused by the same trend.

I will get in touch with the Cython developers to understand what should be the correct configuration for a project that requires Cython at build and packaging time, but doesn't when installing a project whose code has been generated already. Your input is also welcome if you are familiar with the problem.

**Comment by dvarrazzo** [comment]
Maybe a possible solution is to make use of the [Build-time dependencies](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-time-dependencies) features also defined in PEP 518.

**Comment by dvzrv** [comment]
Maybe we're just holding it wrong (while building)...

To understand this all correctly (as I'm not the maintainer of the package usually): is psycopg required if one has psycopg-c installed (and vice-versa)?

**Comment by dvzrv** [comment]
While looking at the source tarball for psycopg-c, I noticed that the build system dependency is definitely cython>=3.0.0a11 which means that using PEP517 build backends, the build will fail if it is not provided.

When using the deprecated `python setup.py build` way, setuptools attempts to download/install missing deps using pip (which is what we want to circumvent).

This unfortunately means, that downstreams are forced to package prerelease versions of cython or not provide psycopg-c at all :S

**Comment by dvarrazzo** [comment]
Yes, `psycopg` is required. `psycopg-c` is a (very suggested) speedup module.

In term of artifacts, the `psycopg` distribution will install the `psycopg` Python package, the `psycopg-c` distribution will install an internal `psycopg_c` package, containing optimized functions and objects that `psycopg` can detect at import time.

Does arch packages psycopg starting from the `psycopg-c` package distributed on PyPI or from the tag in the psycopg git repository?

**Comment by dvarrazzo** [comment]
> This unfortunately means, that downstreams are forced to package prerelease versions of cython or not provide psycopg-c at all :S

Definitely something I don't want. I think we should look into providing a PEP-517 build backend doing the right thing.

**Comment by dvarrazzo** [comment]
There are a few discussions open about Cython and the build system: see cython/cython#2531 for example. This seems the most up-to-date thread and hasn't received updates in more than 4 years though.

**Comment by 0dminnimda** [comment]
> Maybe a possible solution is to make use of the [Build-time dependencies](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-time-dependencies) features also defined in PEP 518.

Yes, it's recommended to use them for packages that use cython as a building tool
https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html?highlight=toml#basic-setup-py

**Comment by dvarrazzo** [comment]
@0dminnimda the documentation regarding [Distributing Cython modules](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html?highlight=toml#distributing-cython-modules) presents two scenarios:

- if you distribute just the c file, put together a standard setup.py:

```python
from setuptools import Extension, setup

setup(
    ext_modules = [Extension("example", ["example.c"])]
)
```

- if you distribute the `pxd`, have `Cython` as build dependency in the `pyproject.toml` and  distribute the pyx:

```toml
[build-system]
requires = ["setuptools", "wheel", "Cython"]
```

```python
setup(
    package_data = {
        'my_package': ['*.pxd'],
        'my_package/sub_package': ['*.pxd'],
    },
    ...
)

```

- then they have an example showing how to hack up the `setup.py` in order to cythonize on demand:

```python
from setuptools import Extension, setup

USE_CYTHON = ...   # command line option, try-import, ...

ext = '.pyx' if USE_CYTHON else '.c'

extensions = [Extension("example", ["example"+ext])]

if USE_CYTHON:
    from Cython.Build import cythonize
    extensions = cythonize(extensions)

setup(
    ext_modules = extensions
)
```

this example shows a non-standard way to proceed.

Now, the use case we have to provide are two:

- installation for development, from a git checkout, containing `pyproject.toml` and the `*.pyx` files.

- installation from a sdist bundle: such bundle contains `pyproject.toml` and the `*.c` files, but not the `*.pyx` file.

and we would like, in both case, for installation to work out-of-the-box. We covered these two scenarios using the trick of checking if a `*.pyx` file exists, instead of asking the user to specify a `USE_CYTHON` env var or something like that. What @dvzrv has reported is that, even if we don't need Cython when installing from a sdist bundle, pip will install it anyway.

I seem to understand that the only way to cover both scenarios is to have two `buid-system.requires` entries:

- one containing Cython, to use at development time. This will be used to build the *.c to include in the sdist. If a new version of Cython breaking the build was released, it would be caught by the packaging pipeline.
- one not containing Cython, to distribute with the package, because the C files we distribute don't require Cython.

It seems that the [`get_requires_for_build_wheel` hook defined in PEP 517](https://peps.python.org/pep-0517/#get-requires-for-build-wheel) would allow to tell apart the two cases. I will try to bundle an [in-tree build backend](https://peps.python.org/pep-0517/#in-tree-build-backends) with `psycopg-c` so that Cython can be considered a dependency only when building from the .git checkout and not when building from the sdist package.

**Comment by 0dminnimda** [comment]
`get_requires_for_build_wheel` seems like a nice way to resolve this!
Another, way to go about this whould be to make a separate file with dev build requerements, but this will introduce the inconvenience that `.toml` files were ment to solve
