### ISSUE TITLE
Disconnected database when a ConnectionPool is already instantiated does not trigger any ConnectionError or ConnectionTimeout

### ISSUE THREAD

**Issue by JeTondsLeGazon** [psycopg/psycopg#481]
### Subject
`ConnectionPool` connection when we have a disconnected database

### Description
If I have a healthy database and I create a psycopg `ConnectionPool` with a valid connection string, then everything works perfectly. When I want to create a connection either via `.connect()` (context manager) or `.getconn()` followed by `.putconn(my_connection)`, this works well.

However, if after doing all the above I kill/drop/disconnect my database, the next try for a connection will still work and I notice the problem only when doing a query.
Currently, only by calling **twice** the `.getconn()` method do I get an error.

### Expected behaviour
When my `ConnectionPool` is already instantiated, I would expect it to immediately throw an error when I try to connect and the database is unhealthy.

### Misc
I may be missing something as I am new to psycopg but I think this should be fixed. I can try to provide some code if needed.

**Comment by dvarrazzo** [comment]
This behaviour [is documented](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#connection-quality). We don't check connections on getconn(), because it takes an extra roundtrip.

I am considering that someone might want to pay the check penalty in exchange of being given a working connection. I will consider if that can be added as an option.

**Comment by JeTondsLeGazon** [comment]
Of course this was simply in the doc... Sorry for the dumb question.
Thank you very much!
