### ISSUE TITLE
Add integration tests with Django

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#489]
See https://github.com/psycopg/psycopg/issues/487 for an example of what I wouldn't like to see happening.

We all love (but hate (but love)) semver, but it would be nice to check for accidental breakages.

Testing would slow down. Maybe we should add an "integration tests" workflow to run before release and daily on cron?

@pauloxnet, @apollo13  would you like to help me with this? Either providing a MR or suggesting a "script" procedure to run a Django+psycopg test, and which versions to test? Feel free to extend the "invitation" to whoever might want to help with this task.

Thank you very much!

**Comment by pauloxnet** [comment]
First of all, I try to suggest also involving @felixxm and @charettes who have worked much more than me on the PR to add support for Psycopg 3.1 in Django 4.2.

**Comment by apollo13** [comment]
Sure thing, this would be great. Since psycopg has a stellar track record I wouldn't overdo testing. In that sense I would only test against the latest Django LTS and main. Do you have an example workflow that I could start extending to add Django support? I also think that a weekly run plus manual (if possible via actions) should be more than enough and would probably save a tree or two.

**Comment by dvarrazzo** [comment]
Hello! I've seen that Django LTS has been released, and I'm really proud about that. Amazing work, the whole Django team, but especially you, @pauloxnet and @apollo13, who have been really instrumental to make it happen!

I would like to make sure to not break the spell now... Is there any plan to progress on this test integration? FYI SQLAlchemy people have added a 3rd party integration workflow and it would be great to have Django tests there, covering whatever you deem useful to cover.

**Comment by dvarrazzo** [comment]
Closed by #549.
