### ISSUE TITLE
Enum types not cast when using class_row factory

### ISSUE THREAD

**Issue by MaartenUreel** [psycopg/psycopg#496]
I created a cursor using the class_row row_factory:
```python
with db.cursor(row_factory=class_row(RateInfo)) as cur:
    cur.execute("SELECT r.setup, r.rate_per_minute, r.category FROM rateplan_rates r")
    result = cur.fetchone()
```

I have defined these models:
```python
class RateCategory(Enum):
    NationalFixed = 1
    NationalMobile = 2
    International = 3
    Premium = 4
    Internal = 5

@dataclass
class RateInfo:
    setup: Decimal
    rate_per_minute: Decimal
    category: RateCategory
```

I would expect that result.category is of type RateCategory, but instead it is an `int`.

I have a simple workaround for this:
```python
@dataclass
class RateInfo:
    setup: Decimal
    rate_per_minute: Decimal
    category: RateCategory

    def __post_init__(self):
        if isinstance(self.category, int):
            self.category = RateCategory(self.category)
```

But it would have been nice that psycopg picked this up nicely internally.

(I shortened / simplified the code to explain)

**Comment by dvarrazzo** [comment]
Hello,

If you have a postgres equivalent of RateCategory you can use [enum adaptation](https://www.psycopg.org/psycopg3/docs/basic/adapt.html#enum-adaptation).

If you don't, I believe this falls outside psycopg scope. It can be worked around in many ways:

- using pydantic instead of data classes, this feature _should_ be supported;
- you can write a factory function or classmethod `from_db()`, which in this case is equivalent to what you have done with the constructor, but you can customize it even better to fit the way the database is queried;
- you can use SQLAlchemy and its more complex data mapping.

It would be arguably cool, but this is absolutely not a trivial feature to implement. Psycopg creates Python types based on the information obtained from the database (that's why you win the Python enum if you have a compatible Postgres enum). Augmenting psycopg so that the mapping could be obtained by both Postgres info and by Python introspection is a major work, and the Python-side introspection is covered more than adequately by projects such as Pydantic: I don't think we could do better than what they do already.

**Comment by MaartenUreel** [comment]
You are right, pydantic does the job well. I learned something today :)

Thanks!
