### ISSUE TITLE
Mark test_sched{,_error} as timing sensitive

### ISSUE THREAD

**Issue by mweinelt** [psycopg/psycopg#502]
Some time ago on 3.0.16 I disabled these two tests (the sync variants) on our nixpkgs darwin builders, because they proved racy.

```python
_______________________________ test_sched_error _______________________________
caplog = <_pytest.logging.LogCaptureFixture object at 0x197218a90>
    @pytest.mark.slow
    def test_sched_error(caplog):
        caplog.set_level(logging.WARNING, logger="psycopg")
        s = Scheduler()
        t = Thread(target=s.run, daemon=True)
        t.start()
        results = []
        def worker(i):
            results.append((i, time()))
        def error():
            1 / 0
        t0 = time()
        s.enter(0.1, partial(worker, 1))
        s.enter(0.4, None)
        s.enter(0.3, partial(worker, 2))
        s.enter(0.2, error)
        t.join()
        t1 = time()
        assert t1 - t0 == pytest.approx(0.4, 0.1)
        assert len(results) == 2
        assert results[0][0] == 1
>       assert results[0][1] - t0 == pytest.approx(0.1, 0.1)
E       assert 0.11003494262695312 == 0.1 ± 1.0e-02
E         comparison failed
E         Obtained: 0.11003494262695312
E         Expected: 0.1 ± 1.0e-02
tests/pool/test_sched.py:93: AssertionError
```

Due to further complications (I'm still waiting for a proper traceback) we are now contemplating disabling `timing` sensitive tests. That is when I noticed these tests are only marked `slow`, when their implementation still looks to me like it would be timing sensitive. Feel free to correct me if that impression is wrong.

> "timing: the test is timing based and can fail on cheese hardware",

I can also guarantee you that our build machines are not cheese hardware and are just somewhat busy most of the time.

Wondering if `pytest-rerunfailures` would be a reasonable escape hatch here for us downstream.

**Comment by dvarrazzo** [comment]
Hello,

I haven't seen that test fail, but that might be because on Windows and macOS (where the time-sensitive jobs tend to fail, maybe because Github has very well used hardware for those jobs) all pool tests might be skipped.

Interesting that your tests fail on Darwin too. Maybe there's something about macOS scheduler/timers that makes these tests not as predictable as on Linux?

Feel free to open a MR to mark all the tests you find brittle with `@pytest.mark.timing`.

I have tried all rerun failure plugins and they all have problems with async tests - see https://github.com/pytest-dev/pytest-rerunfailures/issues/154 for instance. Until some time ago, we used [a retry fixture](https://github.com/psycopg/psycopg/blob/6cf9ea8c333d70640ab26ebf5e47359ec20e9a79/tests/conftest.py#L57-L69) on specific tests considered brittle, but [we got rid of everything](https://github.com/psycopg/psycopg/commit/148f40bc6245641b10c0ec438c537af5fcaa15a9) in favour of a good old `pytest --lf`:

https://github.com/psycopg/psycopg/blob/fd1659118e96a48f22b4e67ff17c2cdab8bd0e84/tools/build/ci_test.sh#L25-L29
