### ISSUE TITLE
TypeInfo has different types depending on postgres local settings

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [psycopg/psycopg#503]
Under different locales, for example `C`, the return types of the query in `psycopg._typeinfo.TypeInfo._fetch(_async)`are bytes instead of strings which means that the [example](https://www.psycopg.org/psycopg3/docs/basic/pgtypes.html#hstore-adaptation) from the psycopg docs for hstore does not work. `psycopg.types.array.register_array` expects the attributes of `TypeInfo` to be strings and attempts to encode them. Normally I use `en_US.UTF-8` but I neglected a parameter to `initdb` so I discovered this. I've since changed my configuration but the problem here remains.

I'd be happy to submit a PR for this if it is an actual bug and not intended behavior, but it might take me a bit - this is a busy week for me.

**Comment by dvarrazzo** [comment]
Hello,

more precisely, I think, you get bytes when the connection encoding is sql_ascii. It should be independent from the locale. Can you confirm that your connection encoding is sql_ascii?

And yes, I'd say it's unexpected. The right thing to do would be to change the connection encoding to anything but sql_ascii using a `set local` statement in the transaction, so that, at the end of the transaction, the connection will be restored to whatever it was before entering it.

Putting together a repro in the test suite...

**Comment by rafmagns-skepa-dreag** [comment]
@dvarrazzo appreciate your quick response and turnaround on this!

**Comment by dvarrazzo** [comment]
@esabol Returning bytes from queries in sql_ascii connection is a feature. If you want normal strings, use a different client encoding *for the connection* (you don't need to change the encoding of the database). For instance you can use the `PGCLIENTENCODING` env vars:

```
# This is my normal one
$ psql -AXqt -c "show client_encoding"
UTF8

# This is one I can arbitrarily select
$ PGCLIENTENCODING=latin1 psql -AXqt -c "show client_encoding"
LATIN1
```

**Comment by esabol** [comment]
> Returning bytes from queries in sql_ascii connection is a feature.

It doesn't seem like a very useful one to me, but ok. Thanks for the reply.

**Comment by dvarrazzo** [comment]
> It doesn't seem like a very useful one to me, but ok. Thanks for the reply.

Have you read the postgres documentation of what the sql_ascii encoding is?
