### ISSUE TITLE
FeatureNotSupported: cached plan must not change result type - how to handle?

### ISSUE THREAD

**Issue by mikkelam** [psycopg/psycopg#511]
I'm wondering what's the best way to handle the above error. I'm often updating my DB schema while my API with a psycopg connection pooler is running.

What's the best strategy for handling the above? Do i need to catch that error and re-start my connection pool or is there a way to automatically handle it somehow?

Thanks for this amazing project btw!

**Comment by dvarrazzo** [comment]
Thank you very much! I see, interesting mode of failure...

I think that the problem is caused by [prepared statements](https://www.psycopg.org/psycopg3/docs/advanced/prepare.html) which get broken by the changes in the schema.

You must disable them by passing `prepare_threshold=None` at connection creation (in the pool you can use `kwargs={"prepare_threshold": None}`).

If you are sure about which queries use the tables whose schema change, you can also use `execute(..., prepare=False)` on those queries only.
