### ISSUE TITLE
Tuple param not being formatted. Raising psycopg.errors.SyntaxError

### ISSUE THREAD

**Issue by jgmills98** [psycopg/psycopg#522]
Hello,

I am trying to run a query that performs `record in record` but it looks like the tuple query param is not being formatted and is sent to the DB as a literal `$1` in the following simplified example.

```
with conn.cursor() as curs:
    query = "SELECT (10,20) IN %s;"
    tups = ((3, 31), (10, 20))
    curs.execute(query, (tups,))
```

This raises the following exception:
```
  File "{my_path}/.venv/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.SyntaxError: syntax error at or near "$1"
LINE 1: SELECT (10,20) in $1;
```

Note the following snippet works as expected in psycopg2.

My psycopg version is `3.1.8` and I've reproduced in python `3.11.2` and `3.10.10`

**Comment by jgmills98** [comment]
Forgo

**Comment by jgmills98** [comment]
Accidentally closed....

**Comment by dvarrazzo** [comment]
Yes, that's not supported. You can find the right way to do it in the documentation, where it says "[you cannot use IN with a tuple](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#you-cannot-use-in-s-with-a-tuple)".

**Comment by jgmills98** [comment]
@dvarrazzo 

Sorry about that. I missed that when reading the docs.

Im still not able to recreate the functionality I want using Any
```
curs.execute("SELECT (10,20) = ANY(%s)", [[[10,20],[10,21]]])
```
raises
```
psycopg.errors.UndefinedFunction: operator does not exist: record = smallint
```

I also tried `[([10,20],[10,21])]` as the payload and this was raised:
```
psycopg.errors.InvalidTextRepresentation: malformed array literal: "("{10,20}","{10,21}")"
DETAIL:  Array value must start with "{" or dimension information.
```

**Comment by dvarrazzo** [comment]
Yes, postgres considers nested arrays as flat when unnesting, so you get the error *operator does not exist: record = smallint*. Lists of tuples can't be adapted either, with postgres raising the error *input of anonymous composite types is not implemented*.


I've played a bit with the problem and maybe you can reproduce the feature using [`unnest(array, array, ....)`](https://www.postgresql.org/docs/15/queries-table-expressions.html#QUERIES-TABLEFUNCTIONS), which returns a table-like object. For instance this works:

```python
cur.execute(
    "select * from pg_attribute where (attrelid, attname) = any(select * from unnest(%s, %s::text[]))",
    [[1255,1255],["oid","proname"]]
)
```

the `text[]` cast is necessary because psycopg 3 uses the unknown oid for strings.

Unnest returns a table-like object, so you can use a join too:

```python
cur.execute(
    "select * from pg_attribute a join unnest(%s, %s::text[]) u(x,y) on (a.attrelid, a.attname) = (u.x, u.y)",
    [[1255,1255],["oid","proname"]]
)
```

Maybe this pattern is worth being mentioned in the docs.
