### ISSUE TITLE
Connection pool timeout should be `Optional`

### ISSUE THREAD

**Issue by rpmrmartin** [psycopg/psycopg#529]
Connection pools accept `None` to indicate no timeout. However, since psycopg_pool 3.1.6, type checkers flag this as an error.

```python
from psycopg_pool import ConnectionPool

ConnectionPool(timeout=None)
```

Pyright:

> Loading configuration file at /app/pyrightconfig.json
> Assuming Python version 3.11
> Assuming Python platform Linux
> Auto-excluding **/node_modules
> Auto-excluding **/__pycache__
> Auto-excluding **/.*
> Searching for source files
> Found 1 source file
> pyright 1.1.300
> /app/EtlProcess/Main.py
>   /app/EtlProcess/Main.py:616:24 - error: Argument of type "None" cannot be assigned to parameter "timeout" of type "float" in function "__init__"
>     Type "None" cannot be assigned to type "float" (reportGeneralTypeIssues)
> 1 error, 0 warnings, 0 informations 
> Completed in 0.705sec

**Comment by dvarrazzo** [comment]
No, connection pool doesn't accept `None` to indicate no timeout. It only takes a float, defaulting to 30 seconds. That's [how is documented](https://www.psycopg.org/psycopg3/docs/api/pool.html#psycopg_pool.ConnectionPool) and [how is implemented](https://github.com/psycopg/psycopg/blob/10fa0e7f6a2b489304eedc2715c74a34f1d28f15/psycopg_pool/psycopg_pool/pool.py#L43).

If you pass None, and, as a side effect, you get no timeout, it's only an implementation accident, it's not by design, and might change in the future. Pyright is right.
