### ISSUE TITLE
Automatically adapt Python dict to PostgreSQL JSON

### ISSUE THREAD

**Issue by danielkauffman** [psycopg/psycopg#541]
In psycopg2, I was able to automatically adapt Python dict to PostgreSQL JSON using:

```python
psycopg2.extensions.register_adapter(dict, psycopg2.extras.Json)
```

In psycopg3, I'm having trouble implementing the same functionality. This seems correct:

```python
connection.adapters.register_dumper(dict, psycopg.types.json.JsonDumper)
```

However, when I pass a Python dict to the cursor,  the above runs JsonDumper but throws:

```python
AttributeError: 'dict' object has no attribute 'dumps'
```

When I look at _JsonDumper here:

> https://github.com/psycopg/psycopg/blob/master/psycopg/psycopg/types/json.py#L120

That seems to be running something like dict.dumps() instead of json.dumps(dict). But dict does not have a dumps() method and json.loads() returns a dict.

Is JsonDumper intended to handle this pattern out-of-the-box? Or do I need to override the class? This seems to work:

```python
class JsonDumper(psycopg.types.json.JsonDumper):
    def dump(self, obj) -> bytes:
        dumps = self.dumps
        return dumps(obj).encode()

connection.adapters.register_dumper(dict, JsonDumper)
```

**Comment by dvarrazzo** [comment]
Uhmm... it seems you are right: this is an use case we overlooked.

A more precise way to do the same, respecting more of the json and connection features, is subclassing the adapter by adding the wrapper internally:

```python
from psycopg.types.json import Jsonb, JsonbDumper

class DictJsonbDumper(JsonbDumper):
    def dump(self, obj):
        return super().dump(Jsonb(obj))

conn.adapters.register_dumper(dict, DictJsonbDumper)

conn.execute("select %s", [{}]).fetchone()
({},)
```

we should think about a better interface for the feature, if we want to reinstate it.

**Comment by danielkauffman** [comment]
@dvarrazzo Thank you!

The interface for psycopg2 seems reasonable... in which case simply add `DictJsonDumper` and `DictJsonbDumper` to https://github.com/psycopg/psycopg/blob/master/psycopg/psycopg/types/json.py and document in https://www.psycopg.org/psycopg3/docs/basic/adapt.html#json-adaptation

```python
# To automatically adapt Python dict to PostgreSQL JSON or JSONB use one of the following.
# This changes the default handling for dict.
connection.adapters.register_dumper(dict, DictJsonDumper)
connection.adapters.register_dumper(dict, DictJsonbDumper)
```

The only wrinkle I see with the above is the awkward naming if dumping another type (such as a list) to JSON. For example:

```python
connection.adapters.register_dumper(list, DictJsonDumper)
```

When I see that code, I wonder why a list is being dumped using a Dict* dumper. That suggests creating synonyms for `DictJsonDumper` as `ListJsonDumper`, `DatetimeJsonDumper`, etc. Or perhaps `ObjJsonDumper`. But `ObjJsonDumper` seems awkward for the most common use case when converting dict to JSON.

Perhaps `JsonDumper` could be modified to support this use case using simply:

```python
connection.adapters.register_dumper(dict, JsonDumper)
```

I really like how that looks, there is no confusion with naming, and the code is very similar to psycopg2.

**Comment by dvarrazzo** [comment]
> Perhaps JsonDumper could be modified to support this use case using simply:
>
> `connection.adapters.register_dumper(dict, JsonDumper)`
> 
> I really like how that looks, there is no confusion with naming, and the code is very similar to psycopg2.

Yes, I think this is the interface we should give it. The `JsonDumper` should either expect a `Json` wrapper or anything that supports json adaptation.

**Comment by danielkauffman** [comment]
Yes, and in `JsonDumper` this could perhaps be as simple as if `obj` doesn't have a `dumps` method, use the `Json` wrapper to add the `dumps` method.

**Comment by dvarrazzo** [comment]
Probably so. I want to write tests to make sure that features such as [`set_json_dumps()`](https://www.psycopg.org/psycopg3/docs/api/types.html#psycopg.types.json.set_json_dumps) are respected even when there's no wrapper.

**Comment by dvarrazzo** [comment]
Heads up:

the easy fix is available in #551 and, afaics, it's all we can do in psycopg 3.1 (without adding new interfaces).

IMO it is not optimal because it is not affected by `set_json_dumps()`: dicts (or other objects) registered using JsonDumper and friends would only get dumped using the stdlib `json.dumps()` function, if `set_json_dumps()` is used with a specific scope; if `set_json_dumps()` is used with the global scope instead it would affect dict dump too.

```python
set_json_dumps(someotherlib.dumps)
connadapters.register_dumper(dict, JsonDumper)  # it uses someotherlib.dumps

set_json_dumps(someotherlib.dumps, conn)
conn.adapters.register_dumper(dict, JsonDumper)  # it uses stdlib json.dumps
```

In order to register a custom dumps function on dict in a restricted scope, it is necessary to create a JsonDumper subclass:

```python
class MyJsonDumper(JsonDumper):
    _dumps = someotherlib.dumps

    # or, alternatively:

    def __init__(self, cls, context = None):
        super().__init__(cls, context)
        self.dumps = someotherlib.dumps
```

which is not documented, and it's probably too much an implementation detail to expose and commit to.

In psycopg 3.2 we can add more features, so we can figure out a better way to do it.

My proposal would be to add an optional `types` argument to `set_json_dumps()` to specify which objects registering the dumper on:

```python
def set_json_dumps(
    dumps: JsonDumpsFunction,
    context: Optional[abc.AdaptContext] = None
    classes: Optional[Sequence[type]] = None
) -> None:
    ...
```

If `classes` is not specified, it would default to `[Json, Jsonb]`, which would maintain the current behaviour.

What do you think?

**Comment by dvarrazzo** [comment]
Not quite, but the effect is the same. `set_json_dumps()` sets the dumps function on the JsonDumper classes, which is the one normally used. The Json[b] wrappers have an optional dumps function, which is used, if set, in preference to the dumper one.

If the dumps function was set on the wrappers only, we would be in a worse situation now, because with no wrapper we couldn't specify a function for dict or for other objects.

Implementation-wise, `set_json_dumps()`, called without context, changes the dumps function used by the Dumpers. If a context is specified, it creates Dumper subclasses and registers them to the specified context.

> might be confusing because the semantics for set_json_dumps() would change from "change the dumps function" to "change the dumps functions and/or register adapters for the specified types" but there is already an interface for registering adapters for the specified types.

Actually this is what `set_json_dumps()` does: it creates dumper classes on the fly and registers them for the specified types, which, at the moment, are only Json and Jsonb, but we might make this list customisable.

**Comment by dvarrazzo** [comment]
Not quite, but the effect is the same. `set_json_dumps()` sets the dumps function on the JsonDumper classes, which is the one normally used. The Json[b] wrappers have an optional dumps function, which is used, if set, in preference to the dumper one.

If the dumps function was set on the wrappers only, we would be in a worse situation now, because with no wrapper we couldn't specify a function for dict or for other objects.

Implementation-wise, `set_json_dumps()`, called without context, changes the dumps function used by the Dumpers. If a context is specified, it creates Dumper subclasses and registers them to the specified context.

> might be confusing because the semantics for set_json_dumps() would change from "change the dumps function" to "change the dumps functions and/or register adapters for the specified types" but there is already an interface for registering adapters for the specified types.

Actually this is what `set_json_dumps()` does: it creates dumper classes on the fly and registers them for the specified types, which, at the moment, are only Json and Jsonb, but we might make this list customisable.

---

Mashing together some test code, this interface would create and ambiguity though. All these functions know that the Json wrapper must dump with the json type oid (thanks to the JsonDumper), Jsonb wrapper must dump with the jsonb type oid (thanks to the JsonbDumper). But if we passed `dict` to the `set_json_dumps()` function, it wouldn't know if the user wants to dump `dict` as `json` or as `jsonb`.

So maybe it would be better to leave this function untouched and define a stable interface for JsonDumper...
