### ISSUE TITLE
ImportError: no pq wrapper available

### ISSUE THREAD

**Issue by ClodoaldoPinto** [psycopg/psycopg#574]
I just upgraded `pgadmin` in Centos 8 and I'm getting the error in the title when accessing the site.
[http_error_log.txt](https://github.com/psycopg/psycopg/files/11586064/http_error_log.txt)
I searched for `libpq` and found these:
```
# find / -name *libpq*
/usr/lib64/libpq.so.5.15
/usr/lib64/libpq.so.5
/usr/lib64/libpq.so
/usr/share/locale/cs/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/de/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/el/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/es/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/fr/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/it/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/ja/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/ka/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/ko/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/ru/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/sv/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/uk/LC_MESSAGES/libpq5-15.mo
/usr/share/locale/zh_CN/LC_MESSAGES/libpq5-15.mo
/usr/pgadmin4/venv/lib/python3.9/site-packages/psycopg_c/pq/libpq.pxd
/usr/pgsql-13/lib/libpq.so.5
/usr/pgsql-13/lib/libpq.so.5.13
/usr/pgsql-13/lib/libpqwalreceiver.so
/usr/pgsql-13/share/locale/cs/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/de/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/es/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/fr/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/it/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/ja/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/ko/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/ru/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/sv/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/tr/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/uk/LC_MESSAGES/libpq5-13.mo
/usr/pgsql-13/share/locale/zh_CN/LC_MESSAGES/libpq5-13.mo
```
I added `/usr/pgsql-13/lib` to the path:
```
# echo $PATH
/usr/pgsql-13/bin:/usr/pgsql-13/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/var/lib/snapd/snap/bin:/root/bin
```
I have `psycopg3` installed:
```
# dnf list \*psycopg3\*
...
Last metadata expiration check: 1:13:29 ago on Sun 28 May 2023 09:45:57 PM GMT.
Installed Packages
python3-psycopg3.noarch             3.1.9-1.rhel8             @pgdg-common
```
What am I missing?

**Comment by dvarrazzo** [comment]
```
- couldn't import psycopg 'c' implementation: /usr/pgadmin4/venv/lib64/python3.9/site-packages/psycopg_c/pq.cpython-39-x86_64-linux-gnu.so: undefined symbol: PQpipelineStatus
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation:
```

The first refers to a psycopg_c package that has been built on some computer where libpq 14+ was installed, but you are trying to use it on a system with libpq 13 installed.

The second is not installed.

The third I don't know, because you have truncated the error message, but it would have been a reasonable fallback.

I assume you built psycopg_c on a different computer and then copied it there, or built with a pg_config inconsistent with the library installed in the system or the headers found at build time.

I suggest you remove psycopg_c from the pgadmin virtualenv, and do with either pure python installation or the binary installation

> I have psycopg3 installed:

yes, but that's from a package manager; you are using a virtualenv, so I don't expect it to be picked up. However, psycopg is surely installed in the virtualenv, it's just a messed up installation. Installation documentation is [here](https://www.psycopg.org/psycopg3/docs/basic/install.html).

**Comment by ClodoaldoPinto** [comment]
_I assume you built psycopg_c on a different computer and then copied it there, or built with a pg_config inconsistent with the library installed in the system or the headers found at build time._

It was installed with dnf from the pgadmin offical repo. They don't support Centos 8. The last version was working.

I solved it by installing psycopg-binary in the virtualenv.

**Comment by codemaker2015** [comment]
try this,
`pip install psycopg-binary`
