### ISSUE TITLE
Best Practices for Executing SQL Scripts?

### ISSUE THREAD

**Issue by xgnxs** [psycopg/psycopg#578]
let's say I have a sql script `my_script.sql` - what would be the best way to execute it using `psycopg`? most search results relate to `psycopg2`, where you can simply use `cursor.execute(open("my_script.sql", "r").read())`, and not `psycopg3`, where the previous method is not allowed. meta-commands also don't seem to work (ex: `cursor.execute("\\i my_script.sql")`), so I was wondering if there was a better way available using `psycopg3`? I was hoping for some kind of `execute_file` function to exist, but it doesn't seem to. it's possible to read the file and then `cast` the text to a `LiteralString`, but that's definitely more of a workaround, and probably not  a best practice.

thank you!

**Comment by dvarrazzo** [comment]
On Wed, 31 May 2023, 20:33 xgnxs, ***@***.***> wrote:

> let's say I have a sql script my_script.sql - what would be the best way
> to execute it using psycopg? most search results relate to psycopg2,
> where you can simply use cursor.execute(open("my_script.sql", "r").read()),
> and not psycopg3, where the previous method is not allowed.
>
What does it mean it is not allowed? It is. It's a string...

> meta-commands also don't seem to work (ex: cursor.execute("\\i
> my_script.sql")),
>
Yes: meta commands are a psql feature, they are not implemented by the
postgres server.

> so I was wondering if there was a better way available using psycopg3? I
> was hoping for some kind of execute_file function to exist, but it
> doesn't seem to. it's possible to read the file and then cast the text to
> a LiteralString, but that's definitely more of a workaround, and probably
> not a best practice.
>
A file is considered unsafe, as far a static checker is concerned. Don't
use a static checker, or find a way to declare the content of the file
safe. A cast to a LiteralString or wrapping your file reading in a function
declared returning a LiteralString are not a workaround: it is a precise
assumption of responsibility about what you are passing to the database.
See the notes about LiteralString limitations (
https://peps.python.org/pep-0675/#appendix-b-limitations):

The important thing to remember is that LiteralString is not intended to
protect against malicious developers; it is meant to protect against benign
developers accidentally using sensitive APIs in a dangerous way (without
getting in their way otherwise).

**Comment by xgnxs** [comment]
> What does it mean it is not allowed? It is. It's a string...

I suppose "allowed" wasn't the right choice here; let's go with: "where the previous method is highly discouraged, given the added type checks."

I was hoping there was a better / more idiomatic solution than "cast the content as a LiteralString and `execute` it", as that felt more "hacky" than "correct", but if there is no other way, and that currently is the best way to execute a `.sql` file (or content of) using `psycopg3`, then this issue can be closed.

thanks!

**Comment by dvarrazzo** [comment]
On Wed, 31 May 2023, 23:56 xgnxs, ***@***.***> wrote:

> I was hoping there was a better / more idiomatic solution than "cast the
> content as a LiteralString and execute it", as that felt more "hacky"
> than "correct", but if there is no other way, and that currently is the
> best way to execute a .sql file (or content of) using psycopg3, then this
> issue can be closed.
>
Your use case is not unheard of, but a more common use case is to have
queries as hardcoded strings in the code or generated dynamically by a
program, which is a notorious cause of bugs for which the extra check of
LiteralString is welcome imo.

To remain in the same mindset that produced LiteralString (the one of
separating the content that is clearly under the control of the developer
from the one potentially coming from the outside), I guess there could be a
LiteralFile object, which could be used to open only a resource within the
Python package it belongs and returning LiteralString, or doing other
consideration regarding the boundary between good vs. evil.

Of course there is also the need of quick hacks, for which I think you can
consider the static checker like Pinocchio's cricket and just ignore its
petulance...

>
