### ISSUE TITLE
Error on JSON adaptation (INSERT data)

### ISSUE THREAD

**Issue by gamaleonardo** [psycopg/psycopg#607]
Hello,

I'm trying to insert data into a table, using pydantic modelling and class_row as row factory, inspired in psycopg3 documentation (https://www.psycopg.org/psycopg3/docs/basic/adapt.html#json-adaptation):

```python
class MyModel(BaseModel):
    status: Enum = "opened"
    program_data: str = Field(max_length=1)
    sector: str = Field(max_length=4)
    name: str = Field(max_length=30)
    creator_id: str = "N/A"
    ball_path: str = "N/A"

with self.get_conn() as conn:
    with conn.cursor(row_factory=class_row(MyModel)) as cur:
        return cur.execute(
             """
                 INSERT INTO model_table
                 VALUES (%s) 
                 RETURNING id
                  """,
                  [Jsonb(my_model_instance.model_dump())],
         ).fetchone()
```

model_dump(): https://docs.pydantic.dev/latest/usage/models/

And I'm getting the following error:

```
'column "id" is of type integer but expression is of type jsonb
```

Could you please help me on it?
Thank you!

Best regards,
Leonardo

**Comment by dvarrazzo** [comment]
The row_factory relates to what the query returns, and returning a MyModel instead of a tuple. This won't work in your example, because you are only returning a column called id.

Your error is caused by the fact that the parameters is a list with a single value, which is a jsonb value, and you are expecting each value to be inserted into a different column - making strong assumptions about the columns order, which is a pretty brittle assumption as postgres columns cannot be reordered.

All in all you are expecting psycopg to do much more than what it does.

What I suggest is:

1) read psycopg documentation so that you know what it does and what you can expect from it
2) check if in the pydantic documentation there are more info about what you want to do
3) write to pydandic or psycopg mailing lists to ask for help.

This is a bug tracker, and yours is not a bug. I cannot help you further here.
