### ISSUE TITLE
cannot adapt type using placeholder TEXT

### ISSUE THREAD

**Issue by crashbandicode** [psycopg/psycopg#611]
Hello. I have some code that I'm using to bulk insert some data using UNNEST. The column is an array of text and I'm running into this issue where the object isn't serializing properly. I've written a simplified example reproducing the error below. 

If you create a table like:
```
CREATE TABLE foo (
                         name            text,
                         pay_by_quarter  integer[],
                         schedule        text[][]
```

And run the following:

```
import psycopg
from psycopg import ClientCursor
from psycopg.adapt import Dumper

if __name__ == '__main__':

    class TextArrayArray:
        def __init__(self, arr):
            self.arr: list = arr

    class TextArrayArrayDumper(Dumper):
        format = psycopg.pq.Format.BINARY
        def dump(self, obj: TextArrayArray) :
            text_array_array = []
            for text_array in obj.arr:
                text_list = [f'{text}' for text in text_array]
                text_array_array.append("{" + ",".join(text_list) + "}")

            return ("{" + ",".join(text_array_array) + "}").encode('utf-8')

    query = f"""
            INSERT INTO foo(schedule) 
            SELECT * FROM UNNEST(%s::text[])
            """

    conn1 = psycopg.connect(f"dbname=postgres user=postgres password=example host=localhost", cursor_factory=ClientCursor)
    conn1.adapters.register_dumper(TextArrayArray, TextArrayArrayDumper)
    cur = conn1.cursor()
    text_array = TextArrayArray([['a','b'], ['c','d']])
    print(cur.mogrify(query, (text_array,)))
    #cur.execute(query, (text_array,))
```

you'll see an error like `psycopg.ProgrammingError: cannot adapt type 'TextArrayArray' using placeholder '%PyFormat.TEXT' (format: TEXT)` 

I feel like I'm possibly making a silly mistake but have been racking my brain for hours trying different things. Executing the query has the same effect.

**Comment by dvarrazzo** [comment]
You have defined:

```
format = psycopg.pq.Format.BINARY
```

this means that the dumper will produce a binary value, and will be only used when the placeholder `%b` is used.

In order to use `%s` you probably want `psycopg.pq.Format.TEXT`.

There seems to be an error in the error message: it should have read _using placeholder '%t'_... Which is also misleading because you have used `%s` but this is a ClientCursor. I'll review these glitches.

**Comment by dvarrazzo** [comment]
By the way, why don't you just use a nested Python list? The dumper should support it no problem.

**Comment by dvarrazzo** [comment]
> So when I change it to `%b` or `%t` they both give the same error as before.

Yes, because the format declared in your dumper:

```python
    class TextArrayArrayDumper(Dumper):
        format = psycopg.pq.Format.BINARY  # HERE
```

says that this is a binary dumper. However, you are formatting the value as text, with `{}`, so you do want a text dumper. Furthermore, you are using a `ClientCursor`: client cursors only use text dumpers, they cannot used binary dumpers, so a dumper declared BINARY can't be used at all. If you used a normal cursor, then the `%s` placeholder would suggest to dump your object as binary, and it will fail because of the wrong array binary format.

> is an issue (I think) with the UNNEST function not supporting 2d arrays

I see, yes. I think that 2d arrays are not unnested into a sequence of 1d arrays but they are totally unraveled to their scalar components.

**Comment by crashbandicode** [comment]
I see. Thank you for explaining! Very helpful.
