### ISSUE TITLE
Unable to use ZoneInfo with datetime.time

### ISSUE THREAD

**Issue by AsiPanda** [psycopg/psycopg#652]
Since Python 3.9, ZoneInfo can be used as tzinfo of datetime and time objects. 
However, using ZoneInfo with psycopg 3.1.12 results in the following error:

```
../.venv/lib/python3.11/site-packages/psycopg/_queries.py:105: in dump
    self.params = self._tx.dump_sequence(params, self._want_formats)
psycopg_binary/_psycopg/transform.pyx:353: in psycopg_binary._psycopg.Transformer.dump_sequence
    ???
psycopg_binary/_psycopg/transform.pyx:400: in psycopg_binary._psycopg.Transformer.dump_sequence
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: descriptor 'total_seconds' for 'datetime.timedelta' objects doesn't apply to a 'NoneType' object
```

This error is thrown when a `time(13, 1, 1, tzinfo=ZoneInfo("Europe/Prague"))` instance is passed to psycopg, but replacing it with `time(13, 1, 1, tzinfo=timezone(timedelta(hours=1)))` works fine.

**Comment by dvarrazzo** [comment]
That's because the offset of the `Europe/Prague` timezone depends on the date: it could be 1h or 2h east of UTC. Therefore requesting the offset of a time without a date in a certain timezone is indeterminate, you can only request a fixed offset. `ZoneInfo` is correctly supported by datetime objects instead:

```python
>>> conn.execute("select %s + '1 hour'::interval", [datetime(2023, 10, 3, 16, 10, 5, tzinfo=ZoneInfo(key='Europe/London'))]).fetchone()[0]
datetime.datetime(2023, 10, 3, 17, 10, 5, tzinfo=zoneinfo.ZoneInfo(key='Europe/London'))
```

Thank you for the report anyway: we can definitely display a better error message and this should become a DataError rather than a TypeError raised internally. However the behaviour cannot possibly change.
