### ISSUE TITLE
notifies seems to be leaking memory

### ISSUE THREAD

**Issue by mkanoor** [psycopg/psycopg#679]
According to the postgres documentation the notifies need to be freed using PQfreemem https://www.postgresql.org/docs/current/libpq-notify.html
I see that happening in the C implementation [here](https://github.com/psycopg/psycopg/blob/fcda5be26c2fb1cd1ac8fd1582a0af4705aed03c/psycopg_c/psycopg_c/_psycopg/generators.pyx#L288)
I am not sure if the python implementation is freeing it.
There is a huge difference in the RSS between the C version and Python version 

```
PSYCOPG_IMPL=c python3 /tmp/pg_listener.py
pmem(rss=26607616, vms=37343232, shared=10588160, text=4096, lib=0, data=16089088, dirty=0)
pmem(rss=28209152, vms=114458624, shared=11587584, text=4096, lib=0, data=24911872, dirty=0)
pmem(rss=28295168, vms=189960192, shared=11653120, text=4096, lib=0, data=33435648, dirty=0)

PSYCOPG_IMPL=python python3 /tmp/pg_listener.py
pmem(rss=26017792, vms=36089856, shared=9990144, text=4096, lib=0, data=15949824, dirty=0)
pmem(rss=89272320, vms=175132672, shared=11108352, text=4096, lib=0, data=86700032, dirty=0)
pmem(rss=89554944, vms=250634240, shared=11108352, text=4096, lib=0, data=95223808, dirty=0)
```

I was sending 10000 notifies with a payload of about 6000 bytes 
Using: Python 3.9.16
Version: 3.1.12
Linux

```python
import asyncio
import logging
from typing import Any
import psycopg
import psutil
import os
import gc

print(os.getpid())
process = psutil.Process(os.getpid())
print(process.memory_info())
LAST_RSS = process.memory_info().rss


async def main(args: dict[str, Any]) -> None:
    """Listen for events from a channel"""

    async with await psycopg.AsyncConnection.connect(
        host=args["host"],
        dbname=args["dbname"],
        user=args["user"],
        password=args["password"],
        autocommit=True,
    ) as conn:
        counter = 0
        async with psycopg.AsyncClientCursor(connection=conn) as cursor:
            await cursor.execute(f"LISTEN {args['channel']};")
            async for _ in conn.notifies():
                counter += 1
                if counter >= 10000:
                    break

            print(process.memory_info())
if __name__ == "__main__":
    print(psycopg.pq.__impl__)
    asyncio.run(
        main(
            {
                "dbname": "db",
                "host": "localhost",
                "user": "postgres",
                "password": "secret",
                "channel": "my_events",
            },
        )
    )
    gc.collect()
    print(process.memory_info())

```

**Comment by dvarrazzo** [comment]
Ehm... this seems an embarrassing bug indeed :sweat_smile: 

https://github.com/psycopg/psycopg/blob/fcda5be26c2fb1cd1ac8fd1582a0af4705aed03c/psycopg/psycopg/pq/pq_ctypes.py#L603-L610

Not a great chance to run `PQfreemem()` here...

**Comment by dlax** [comment]
Using `mypy --warn-unreachable` could have helped; but it raises 
false-positive issues sometimes.

**Comment by dvarrazzo** [comment]
@dlax Thank you for pointing it out, I didn't know that feature. I gave it a run, and it seems buggy in certain cases, such as reporting line 125 unreachable here (it doesn't if there are two assignments):

https://github.com/psycopg/psycopg/blob/5019cb53e7509e2676109dfb04466818d4eecf9d/psycopg/psycopg/pq/pq_ctypes.py#L122-L125

In other cases our pattern is unconventional, for instance here 138 is unreachable because mypy doesn't know that `raise Rollback` is swallowed by `Transaction.__exit__`:

https://github.com/psycopg/psycopg/blob/5019cb53e7509e2676109dfb04466818d4eecf9d/tests/test_transaction_async.py#L131-L139

Others, who knows... Here line 94 is considered unreachable:

https://github.com/psycopg/psycopg/blob/5019cb53e7509e2676109dfb04466818d4eecf9d/psycopg/psycopg/pq/__init__.py#L86-L95

The `if True:  # ASYNC` pattern surely won't help its job :smile: 

However I will consider giving the codebase a look with it.
