### ISSUE TITLE
Support `row_factory` as argument to `fetchone`, `fetchmany`, `fetchall`

### ISSUE THREAD

**Issue by alexei** [psycopg/psycopg#687]
What do you think about supporting `row_factory` as an argument to `fetchone`, `fetchmany`, `fetchall`?

E.g. given:

```python
@dataclass
class Foo:
    ...


@dataclass
class Bar:
    ...
```

That would result in:

```python
with psycopg.connect(...) as conn:
    with conn.cursor() as cur:
        for f in cur.execute("SELECT * FROM foos").fetchall(row_factory=class_row(Foo)):
            ...

        for b in cur.execute("SELECT * FROM bars").fetchall(row_factory=class_row(Bar)):
            ...
```

vs.

```python
with psycopg.connect(...) as conn:
    with conn.cursor() as cur:
        cur.row_factory = class_row(Foo)
        for f in cur.execute("SELECT * FROM foos").fetchall():
            ...

        cur.row_factory = class_row(Bar)
        for b in cur.execute("SELECT * FROM bars").fetchall():
            ...

        # we need to reset the row factory once we're done
        cur.row_factory = tuple_row
```

I think the point is that usually one needs to query multiple tables, not just one.

**Comment by dvarrazzo** [comment]
I do see your point. Let me ramble...

It does make sense that the point where the type is declared is close to the point where it is used.

However cursors are cheap, so you can also write:

```
with psycopg.connect(...) as conn:
    with conn.cursor(row_factory = class_row(Foo)) as cur:
        for f in cur.execute("SELECT * FROM foos").fetchall():
            ...

    with conn.cursor(row_factory = class_row(Bar)) as cur:
        for b in cur.execute("SELECT * FROM bars").fetchall():
            ...
```

Implementation-wise, it's a bit awkward because the row maker was initialized once per result so far, and, with your implementation, one could call

```python
first = cur.fetchone(row_factory=First)
second = cur.fetchone(row_factory=Second)
```

so we should check that the RowFactory is the same object across different calls, in which case we shouldn't create a new RowMaker, which might be an expensive operation. Probably the right place where to store the row_factory (if it isn't already) is the Transformer, so we would leave the cursor's row factory unchanged, in case people would, even more perversely, call:

```python
first = cur.fetchone(row_factory=First)
second = cur.fetchone()  # expecting the cursor's factory to be used
```
 
One positive thing is that it gives a place to set up a row factory for queries executed on the `Connection.execute()` without having to create the cursor explicitly:

```python
# before
conn.cursor(row_factory=Record).execute(query).fetchone()

# after
conn.execute(query).fetchone(row_factory=Record)
```

The previous pattern is still useful to just iterate on the cursor:

```python
for rec in conn.cursor(row_factory=Record).execute(query):
    ...
```

From type annotation point of view it doesn't seem to be a problem: we can overload the `fetch*()` methods to include the variant where `row_factory` is specified.

So, I would say I'm not totally enthusiastic, but also not totally negative about the extension. I don't think it allows to write patterns that were previously unavailable (if you are ok to throw away a cursor, which I usually am, but that might be just my style) but it is sort of a natural place where to set the row factory.

@dlax what do you think about it?

**Comment by alexei** [comment]
Thanks for the response. If cursors are cheap (I did not know that), then using multiple cursors works for me.

On another note - do transactions still work across cursors?

**Comment by dvarrazzo** [comment]
Cursors seem an adequate substitute for the feature requested.
