### ISSUE TITLE
Typing of AsyncConnectionPool is incompatible with pyright

### ISSUE THREAD

**Issue by adriangb** [psycopg/psycopg#708]
```python
from psycopg_pool import AsyncConnectionPool

async def main() -> None:
    async with AsyncConnectionPool() as pool:
        pass
```

```
test.py
  test.py:5:16 - error: Object of type "AsyncConnectionPool[AsyncConnection[TupleRow]]" cannot be used with "with" because it does not implement __aenter__ (reportGeneralTypeIssues)
  test.py:5:41 - error: Type of "pool" is unknown (reportUnknownVariableType)
  test.py:5:41 - error: Variable "pool" is not accessed (reportUnusedVariable)
3 errors, 0 warnings, 0 informations 
```

pyright==1.1.343
psycopg==3.1.16
psycopg-binary==3.1.16
psycopg-pool==3.2.0

**Comment by dvarrazzo** [comment]
This is clearly incorrect:

https://github.com/psycopg/psycopg/blob/aa4d15b8ba9a7f0865aa486c804f46adadc440a9/psycopg_pool/psycopg_pool/pool_async.py#L522

Pyright is pywrong here.

**Comment by adriangb** [comment]
I think the issue is the _Self type and the bound with generics on it. I’m happy to report an issue on pyright.

**Comment by dvarrazzo** [comment]
Thank you very much, very appreciated!

**Comment by adriangb** [comment]
No problem! It might be worth trying to use `typing_extensions.Self` to see if that resolves the problem.

**Comment by adriangb** [comment]
My suspicion is that although the error from pyright is confusing what it's trying to say is "this class doesn't implement the AsyncContextManager API as I expect it to" due to the typing of `_Self`.

**Comment by dvarrazzo** [comment]
That might be, however it's a construct that mypy understand correctly, and mypy is the static checker we use for our codebase.

I don't remember if there was some work done in the past to use `typing.Self`. I assume we tried, but we found some shortcoming. A lot of time has passed since (I can't find a relevant branch) and maybe we had problems with some Python version (3.6, 3.7) that we don't need to support anymore.

Would you like to propose a MR to add `Self` to [`psycopg/psycopg/_compat.py`](https://github.com/psycopg/psycopg/blob/master/psycopg/psycopg/_compat.py) (to be version-guarded on 3.11, as that's when [`typing.Self`](https://docs.python.org/3/library/typing.html#typing.Self) was added to the stdlib) and use it instead of our home-grown `_Self`? You can check if it works on Pyright as expected and, if it passes the mypy check too, it would be a welcome change.

Best would be probably to make the MR for the **maint-3.1** branch, so that the change can be included in a soon-to-be-released 3.1.17, but it would need to support Python 3.7 too, or to find a way to keep the 3.7 compatibility using `_Self`, which might be possible but it's possibly clunky. If you provided that, I would rebase and adapt the change for the master branch.

If you work on master, instead, you would only have to support from Python 3.8 on, but the change will be released in 3.2.0, which might still take a few months.

Thank you very much!

**Comment by adriangb** [comment]
I honestly don’t have the bandwidth to work on this right now. For now I’ve pinned to an older version.

> mypy is the static checker we use for our codebase

Keep in mind that pyright is the type checker that vscode uses and thus that most Python developers use (according to surveys). So even if this project uses mypy having it work correctly with pyright should be a priority. I would rather have less typing, as in previous versions, rather than typing that causes issues for the second most, if not, the most popular type checker.

**Comment by dvarrazzo** [comment]
A warning on a buggy type checker is not a blocker for us.

**Comment by adriangb** [comment]
If you think it’s bug in pyright I would encourage you to discuss it with Eric directly. I’m just a reporter here and I’m being told by both projects that the other is to blame.

**Comment by dvarrazzo** [comment]
Making an attempt to use `typing.Self`, regardless of whether it will fix PyRight or not.

**Comment by adriangb** [comment]
I can check how it interacts with pyright tomorrow :)

**Comment by dvarrazzo** [comment]
Thank you, @adriangb! You can find the proposed MR in #710.

**Comment by Viicos** [comment]
> I assume we tried, but we found some shortcoming.

As mentioned in the opened PR, seems to be because we can't parametrize `typing.Self`. I think it would require higher kinded TypeVars for this to work, but I'm wondering if a subset of this feature could be supported for this specific use case (maybe by tweaking the semantics of the `Self` specification).

> however it's a construct that mypy understand correctly

But it shouldn't, pyright was correct at emitting a diagnostic. For reference, [here](https://typing.readthedocs.io/en/latest/spec/generics.html#type-variables-with-an-upper-bound) is the section describing the allowed types to the `bound` argument.

**Comment by dvarrazzo** [comment]
@Viicos 

> I'm wondering if a subset of this feature could be supported for this specific use case (maybe by tweaking the semantics of the Self specification).

I was thinking exactly the same. PEP 673 says about [use in generics](https://peps.python.org/pep-0673/#use-in-generic-classes):

> Note that we reject using Self with type arguments, such as Self[int]. This is because it creates ambiguity about the type of the self parameter and introduces unnecessary complexity:
> 
> ```python
> class Container(Generic[T]):
>     def foo(
>         self, other: Self[int], other2: Self,
>     ) -> Self[str]:  # Rejected
>         ...
> ```
>
> In such cases, we recommend using an explicit type for self:
> 
> ```python
> class Container(Generic[T]):
>     def foo(
>         self: Container[T],
>         other: Container[int],
>         other2: Container[T]
>     ) -> Container[str]: ...
> ```

The example they provide to prove the ambiguity is pretty contrived, and a generic self would be extremely useful in practical and unambiguous case. Our case is just, very simply, annotating factory methods returning instances of the class. Something similar to:

```python
class Connection(Generic[T]):
    @overload
    @classmethod
    def connect(cls, row_type: T) -> Self[T]:
       ...

    @overload
    @classmethod
    def connect(cls) -> Self[tuple]:
       ...
```

With the workaround suggested, every subclass must redefine `connect()` to fix the return value annotation.


>> however it's a construct that mypy understand correctly

> But it shouldn't, pyright was correct at emitting a diagnostic.

Maybe, but it just means that it's valid Python that cannot be represented in pyright model. For sure we will not stop offering a feature because Pyright cannot handle it.

**Comment by adriangb** [comment]
For what it’s worth I agree that generic self should be allowed but the pep is very clear about it not being allowed. Pyright is choosing to be correct while mypy is choosing to be wrong but useful, or maybe it’s a bug and they change the behavior next release, who knows.

If you really want to you can define a constant `MYPY = False` and then do:

```python
MYPY = False
if MYPY:
    # types for mypy
else:
    # types for pyright
```

it’s unfortunate that this is so complicated but that’s the reality of developing a typed library for a language with a type system that is still in flux

**Comment by Viicos** [comment]
> Maybe, but it just means that it's valid Python that cannot be represented in pyright model. For sure we will not stop offering a feature because Pyright cannot handle it.

> it’s unfortunate that this is so complicated but that’s the reality of developing a typed library for a language with a type system that is still in flux

This is what the newly added typing spec (still in progress) is trying to solve. Hence my comment linking the related section in the spec about bound TypeVars. So yes mypy currently handles it but it shouldn't and will probably remove support at some point if as the type checkers will have to comply to this spec at some point.

**Comment by dvarrazzo** [comment]
Psycopg 3.1.17 and psycopg-pool 3.2.1 make use of `typing.Self`, bringing whatever improvement it can bring. In psycopg 3.2 we are preparing to use a TypeVar default ([PEP 696](https://peps.python.org/pep-0696/)) to model the TupleRow as the default type if a row factory is not specified.

We moved to using Self in psycopg 3.1 and, in 3.2, we will use typevar defaults to handle the TupleRow default of the connection (although I'm taking a look to figure out whether we might introduce it in 3.1.1o8 instead).
