### ISSUE TITLE
Support async on Windows

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#76]
Windows asyncio tests don't pass and they are [currently skipped](https://github.com/psycopg/psycopg/blob/5b92c16e3b151dc57ecbbcabddfda27a1751e8c2/tests/conftest.py#L52-L55).

Does async work on Windows at all?

**Comment by CaselIT** [comment]
> Does async work on Windows at all?

It does mostly, but I cannot speck for low-lever network stuff since I don't have much experience on it.
I usually use windows, what kind of issues does it have?

**Comment by dvarrazzo** [comment]
Can you just try to run the psycopg test suite as explained [in the tests readme](https://github.com/psycopg/psycopg/tree/master/tests) and see what fails? You will have to disable the skipping code linked in this issue's description.

On the github action runner all the asyncio tests fail with some message of the tone that the loop isn't running. I don't know if it's an issue of the runner, of python+win+asyncio, or of psycopg code.

**Comment by CaselIT** [comment]
I guess I'll need to figure out how to install the compiler chain or libpq.

psycopg-binary cannot be used as the network implementation while using the repository version of psycopg right?

**Comment by dvarrazzo** [comment]
You shouldn't need a compiler: you can use the pure Python version. You only need the `libpq.dll`, which is installed by installing PostgreSQL on Windows. I don't know the rules to find it: I think it should be in a `%PATH%` dir.

**Comment by CaselIT** [comment]
oh nice, I'll try that. I currently use docker for postgress.

**Comment by dvarrazzo** [comment]
You can probably download the postgres package for window, unpack it, and extract the `libpq.dll` from there...

**Comment by CaselIT** [comment]
It seems that the issue is the usage of add_writer / add_reader: https://docs.python.org/3/library/asyncio-platforms.html#windows

> ProactorEventLoop has the following limitations:
>
>    The loop.add_reader() and loop.add_writer() methods are not supported.

specifying `asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())` in the tests does make most of them pass, except for one that fails with `OSError: [WinError 10038] An operation was attempted on something that is not a socket` as documented in the above link:
`================================== 2 failed, 2926 passed, 166 skipped, 21 xfailed, 4 xpassed in 330.21s (0:05:30) ===================================`
I did not test with pool installed so that accounts for most of the skips

I'm not sure if it's possible to change the event loop in general since I think a thread can have a single loop running so it's the external application that handles creating it, and by default windows uses Proactor (no clue why).

I'm not knowledgeable enough to know if it possible and how to replace `add_writer`, `add_reader` on windows when using proactor.

A quick search brought me to https://bugs.python.org/issue37373 that does offer some solutions on how to do that on windows (private thread with selector event loop). Also in that thread it's linked to an anyio change that added support to proactor https://github.com/agronholm/anyio/commit/da0a792c17b840027030289a2566cf5910880d42 by changing the implementation (it seems I just skimmed it).

My 2 cents is that the thread solution may be good enough, since I expect 95%+ or the usage would be on unix in any case, so something that "just works" on windows would be good enough. If you need help in with testing let me know

**Comment by CaselIT** [comment]
It seems that tornato uses the thread approach: https://github.com/tornadoweb/tornado/pull/2815/files

I'm not sure the same code can be used here (not an expert on licenses)

**Comment by dvarrazzo** [comment]
Would you be able to provide a patch to switch the loop in the test suite? It might also be useful to provide docs to windows users, because it's not psycopg responsibility to choose the loop policy.

It would be even great to warn windows users on connect in case their loop doesn't work.

**Comment by CaselIT** [comment]
Yes, I think I can work on it next week.

Also detecting the type of loop should be easy enough. Do you think adding something similar to the tornado patch is too much work?

**Comment by CaselIT** [comment]
Makes sense. Better windows support can always be added later
