### ISSUE TITLE
Feature Request: add write_rows method to Copy object

### ISSUE THREAD

**Issue by AlexJMohr** [psycopg/psycopg#771]
It would be nice to have a `write_rows` method added to the [Copy](https://www.psycopg.org/psycopg3/docs/api/copy.html#psycopg.Copy) object, for more ergonomic use. Akin to the standard library's `csvwriter` which has both `writerow` and `writerows` methods.

```py
with curs.copy("COPY foo (a, b, c) FROM STDIN") as copy:
    for row in rows:
        copy.write_row(row)
```
Becomes:
```py

with curs.copy("COPY foo (a, b, c) FROM STDIN") as copy:
    copy.write_rows(rows)
```

`Copy.write_rows` would take in iterator of rows and internally would just call `self.write_row(row) for row in rows`.

Happy to make an attempt at a PR if it's wanted.

**Comment by dvarrazzo** [comment]
Probably because I have in mind several different use cases for the Copy object, I see enough scenarios in which people would do something different than `map(copy.write_row, rows)` to make your proposal not very appealing.

One major problem is the interaction with async connections: sometimes you might want to consume a sync generator, sometimes an async one so `write_rows` should either made some introspection operation to figure out the type of generator to consume or it would be only be useful for an arbitrary kind of producer. Unlikely, but someone might also want to consume an async generator of rows to a sync psycopg connection...

Having the loop explicitly unrolled by the user also gives them the opportunity to perform other related operations, such as printing a line of log every 10k lines written or something like that.

Sometimes the source of record is not an iterable, or making it an iterable means jumping through unpleasant hoops. Actually the designed of COPY with the "loop unrolled by the user" was dictated not only by the need of accommodating async operations, but also by the memory of having to write a SAX parser for a huge XML file and feeding psycopg2's `copy_expert()` with its "pulling from a file" interface: I would have loved to have a push interface in that case.

So, all in all, the feature would only save the end user one line of code, and only in the most basic use case of the copy operation. Therefore, I wish to thank you very much for submitting your proposal, but I don't think it would be a valuable addition.

**Comment by AlexJMohr** [comment]
Ah I wasn't aware of the complexities around async. Makes sense, thanks for the explanation.

It would make sense to me to only accept sync generators in sync `Copy.write_rows`, and only accept async generators in `AsyncCopy.write_rows`. If the user wants to do something more complicated than that, then they have to unroll the loop themselves. Same argument if the user wants to do logging or something like that.
