### ISSUE TITLE
couldn't import psycopg 'c' implementation: No module named 'psycopg_c'

### ISSUE THREAD

**Issue by dss010101** [psycopg/psycopg#807]
Im seeing the abvoe error when my app starts.  
```
2024-05-03 18:52:18,885|49821|140021569563520|DEBUG|__init__.handle_error|couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
```
This may be related to this ticket https://github.com/psycopg/psycopg/issues/394, but that ticket is closed and in my case, its not jupyter, but a data webservice using python 3.12 and the latest psycopg:
```
psycopg==3.1.18
psycopg-binary==3.1.18
psycopg-pool==3.2.1
```
I am running in a docker container based on the python 3.12 image (which is a debian bookworm based image)
From google i have seen some recommend installing libpq-dev.  i rebuilt the container with those libraries, but still seeing the error.

I see the following under site-packages:
drwxr-xr-x 6 root root 4096 May  3 03:00 psycopg
drwxr-xr-x 2 root root 4096 May  3 03:00 psycopg-3.1.18.dist-info
drwxr-xr-x 3 root root 4096 May  3 03:00 psycopg_binary
drwxr-xr-x 2 root root 4096 May  3 03:00 psycopg_binary-3.1.18.dist-info
drwxr-xr-x 2 root root 4096 May  3 03:00 psycopg_binary.libs
drwxr-xr-x 3 root root 4096 May  3 03:00 psycopg_pool
drwxr-xr-x 2 root root 4096 May  3 03:00 psycopg_pool-3.2.1.dist-info

Strangely the database connection and queries seem to work still.  So im not sure what this dependency is.
How do i resolve this?

**Comment by dvarrazzo** [comment]
You are not seeing an error, you are seeing a `DEBUG` message. The solution is that you don't look at it: disable logging at debug level if you are not the expected audience. You will see all sort of messages that they are not meant for you.

> Strangely the database connection and queries seem to work still.

Therefore this is not an error.

**Comment by dss010101** [comment]
Can we turn debug level off for just psycopg?  There are times when I want to increase debug level esp when in development or investigating production issues.

Also, what exactly is causing that/what does it mean?

**Comment by dvarrazzo** [comment]
> Can we turn debug level off for just psycopg? There are times when I want to increase debug level esp when in development or investigating production issues.

For this you need to read the documentation of the `logging` module.

> Also, what exactly is causing that/what does it mean?

For this you need to read the source code of the `psycopg.pq` module.

**Comment by dss010101** [comment]
> > Can we turn debug level off for just psycopg? There are times when I want to increase debug level esp when in development or investigating production issues.
> 
> For this you need to read the documentation of the `logging` module.
> 
> > Also, what exactly is causing that/what does it mean?
> 
> For this you need to read the source code of the `psycopg.pq` module.

I would like to give you some feedback. i hope that you accept feedback in good faith and dont think it's an insult.  
...my limited impressions of my engagement here are...that you tend to be more dismissive than other maintainers/owners of other libraries.  i dont know if you are the owner or creator of this library...but it doesnt leave a good 'first' impression for anyone thinking of using this library - we would be concerned if we do encounter a real issue, whether we would be told to just RTFM.

i mean..u have an error message that reads pretty serious, and you say 'ignore'.
any decent and curious/inquisitive developer would want to know why?  but you say - read the docs.
we use a lot of libraries - we dont always ready every word of the documentation and probably dont want to...thats just reality.

take the feedback and hopefully you or others that maintain/support the product can find benefit from it.

**Comment by dvarrazzo** [comment]
So you don't read documentation, but you want the maintainer of another random library to explain you how they work?

This is a level of entitlement, or an immaturity, that I don't intend necessary to support in my free time.

Please answer a question without taking it as an insult: are you 14? If you are fourteen, then you are immature, and I can spend some time to teach you a few pointers. Sometimes I might have time for that, often I do, and sometimes not.

If you are more than 14, and maybe even a professional, then you should learn that you are responsible for certain things. You have to learn who is the caller and who is the callee of a function call, and whose fault is it when there is an error (in reference to #806, where you pretty much wrote `len(10)` in your code, then you opened a bug to the maintainer of the int type to say that their code is wrong). You should also by now know by now what is an error and what is an internal debug log message which, thanks to the configuration in your own code, you are seeing.. If you don't know what logging is, the documentation of the logging module will tell you, and looking at the source code of a module will also explain things in a more precise way than I can, or want, to use, in a bad bug report.

So, please, communicate me your age so I can refer to you in the most suitable manner, but please know that I have limited time for entitled people who prefer to have a personal hand crafted explanation where good documentation has been written. It shows lack of respect for their time and my time, and I value this respect.

**Comment by dss010101** [comment]
> So you don't read documentation, but you want the maintainer of another random library to explain you how they work?
> 
> This is a level of entitlement, or an immaturity, that I don't intend necessary to support in my free time.
> 
> Please answer a question without taking it as an insult: are you 14? If you are fourteen, then you are immature, and I can spend some time to teach you a few pointers. Sometimes I might have time for that, often I do, and sometimes not.
> 
> If you are more than 14, and maybe even a professional, then you should learn that you are responsible for certain things. You have to learn who is the caller and who is the callee of a function call, and whose fault is it when there is an error (in reference to #806, where you pretty much wrote `len(10)` in your code, then you opened a bug to the maintainer of the int type to say that their code is wrong). You should also by now know by now what is an error and what is an internal debug log message which, thanks to the configuration in your own code, you are seeing.. If you don't know what logging is, the documentation of the logging module will tell you, and looking at the source code of a module will also explain things in a more precise way than I can, or want, to use, in a bad bug report.
> 
> So, please, communicate me your age so I can refer to you in the most suitable manner, but please know that I have limited time for entitled people who prefer to have a personal hand crafted explanation where good documentation has been written. It shows lack of respect for their time and my time, and I value this respect.

i am 52, head of an Enterprise Architect group at a financial company with 4 groups and 80 devs reporting into it.  I am still very hands on, because i try to lead by example, and i enjoy it.   
And this is what i had hoped wouldnt happen.  Feedback is important.  equally important to be able to take feedback.  
you win and you can have the last word

**Comment by raratiru** [comment]
Great! 
Same inquiry in my DEBUG level case. 

I confess that it is a quite alarming  log, even in that level. 

Disturbing also, because although I am not ADHD enabled... 

In the middle of another problem I realized that I may have a bigger one... or not.  
And then wondered... "oh, would it be faster if it used this 'c-related' implementation and I am not using it?". 

Should I read the manual after I debug, let me add a `# TODO: ` here.

... or am I, after all? Dunno.

**Comment by nitsujri** [comment]
> You are not seeing an error, you are seeing a DEBUG message.

```
[DEBUG 2024-07-23 05:33:08,058 __init__.handle_error] couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
```

From something named `handle_error`. For me, I'm not as smart as you and I definitely don't know what's inside something as complex as psycopg. My concern is - Even though all my tests pass, am I missing something that will blow up a query/function that I don't know about and I won't find that out until production?

`psycopg_c` sounds pretty important, but apparently it's not?

I imagine a lot of people will have the same line of thinking and will have to come here to discover it's something we're "supposed to dismiss".

**Comment by Gabri-Or** [comment]
I'm having a weird `no module named psycopg` import error message that I can't explain, and I also have the `couldn't import psycopg 'c' implementation: No module named 'psycopg_c'` message.

I thought maybe they were related since both messages mention the impossibility of importing psycopg, but then I get here and see a maintainer dismiss the second message as something to ignore and tell people "to read the source code of the `psycopg.pq` module" if they want to understand why.

So now I'm lost. 
As someone who clearly lacks the intelligence to read and understand the `psycopg.pq` module I'm imploring: dear overlord of psycopg, supreme expert of PostgreSQL, can you devote a drop of your precious time to help a simpleton like me understand the nature of this cursed (non-error) message?

Oh, just so that you can "refer to me in the most suitable manner", please know that I'm 31.

**Comment by dvarrazzo** [comment]
@Gabri-Or thank you for the morning sarcasm. I have already decided that as when I will get around to touch the codebase I will remove those DEBUG messages. It might make harder to diagnose bugs for people whose imports fail in mysterious manner, but it will still better than having these conversations.

If you see _couldn't import psycopg 'c' implementation: No module named 'psycopg_c'_ it means that you, in your program, have enabled `psycopg` logger to log at DEBUG level. Cases are: 1) you want to debug the internals of psycopg or 2) you have misconfigured your logging system. I assume that the case is the second, therefore... don't do that. The documentation of the [logging](https://docs.python.org/3/library/logging.html) core module explains how to select the loggers and the level of which you read messages. You are not requested to read our source code, but it is reasonable to expect that you know how to use a core module that you are actually using and actively configured.

So yeah, that's confirmed: please don't care about "no module named psycopg_c" because that's a factual statement (not an error - please note the lack of the word "error" in the message) destined to an audience that is not yourself. If something should be raised to your attention it would be an exception.

**Comment by Gabri-Or** [comment]
I hope you didn't get too mad, I was just having a bit of fun 🫶 .

Seriously though, you say that removing the message might make it harder to diagnose bugs, but you see in my case I had an (unrelated) psycopg import error and I got lost because, coincidentally, I had this other import message (not an error, I'll give you this), which was way too similar to just ignore it and way too low-level for me to understand it.

The problem was never the logging, which (if I may boast a little bit) I'm very comfortable configuring by myself, but rather the request to ignore a pretty scary message happening in the presence of a bug.

As a non-expert programmer, I don't know whether you should keep or remove that debug-level message, but if you keep it you should be available to explain its meaning and why we should ignore it, if not by documenting it at least when someone opens an issue like this.

Also, people are curious, so it would be nice to learn a thing or two about how things work even if that knowledge is strictly unnecessary.

Then again this is open source, so I can't tell you that you should be doing anything at all, and I should thank you for maintaining this important library instead.

And btw thanks for answering so quickly, in the meanwhile I managed to solve my unrelated problem so I guess I'm done here

**Comment by baggiponte** [comment]
> I have already decided that as when I will get around to touch the codebase I will remove those DEBUG messages. It might make harder to diagnose bugs for people whose imports fail in mysterious manner, but it will still better than having these conversations.

I think that might be a loss for the ecosystem as a whole. Would you prefer instead if anyone (I can do it too) opened a PR to include a couple of lines of documentation to troubleshoot this and be of future reference? 😊

**Comment by dvarrazzo** [comment]
@baggiponte thank you but this doesn't require documentation: if we document a thing it's interface, this should have been a hidden helper to debug the library.

**Comment by therightmandev** [comment]
> If you see couldn't import psycopg 'c' implementation: No module named 'psycopg_c' it means that you, in your program, have enabled psycopg logger to log at DEBUG level. Cases are: 1) you want to debug the internals of psycopg or 2) you have misconfigured your logging system. I assume that the case is the second, therefore... don't do that. The documentation of the [logging](https://docs.python.org/3/library/logging.html) core module explains how to select the loggers and the level of which you read messages. You are not requested to read our source code, but it is reasonable to expect that you know how to use a core module that you are actually using and actively configured.

Despite all the bad blood between everyone in here, thanks for coming back and explaining that it's related to enabling logging too broadly. I didn't realize that that was the issue until I got to this message of yours, as that logging had been configured by me, but a long time ago.
