### ISSUE TITLE
What am I missing regarding ConnectionPool max_lifetime and FastAPI

### ISSUE THREAD

**Issue by A-Posthuman** [psycopg/psycopg#809]
Hi,

I'm struggling with how to use this ConnectionPool properly with FastAPI. Some example code I'm using  is below. The problem is that whenever the max_lifetime runs out (1 hr by default, by I can cause the issue sooner by setting this lower), my program gets handed a closed connection and then "psycopg.OperationalError: the connection is closed" is thrown when I try to use the connection.

Why is the pool closing the connection, but then still handing it to my program to use instead of replacing it with a new connection? Let me know where I'm going wrong, thanks.

code snippet:
```

from fastapi import FastAPI, Request, Depends, Query, HTTPException
from psycopg_pool import ConnectionPool

@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    pg_pool = ConnectionPool(min_size=4, max_size=8, configure=configure_connection, conninfo="xxxx")
    pg_pool.wait()
    log.info("pg pool ready")
    app.state.pg_pool = pg_pool
    yield  # This yield allows the FastAPI application to run
    # This is executed when the app is shutting down
    app.state.pg_pool.close()  # Close PostgreSQL pool

# Function to configure each new connection
def configure_connection(conn):
    conn.execute("SET ivfflat.probes = 53")
    conn.commit()

# Initialize FastAPI with the custom lifespan context manager
app = FastAPI(lifespan=lifespan)

# Get a db connection from the pool to use
def get_pg_connection(request: Request) -> Any:
    with app.state.pg_pool.connection() as conn:
        # to test if connection works, do a SELECT 1
        with conn.transaction():
            cursor = conn.cursor()
            cursor.execute("SELECT 1")
            return conn

@app.get("/search")
def root_endpoint(query: str = Query(default=None, description="The query parameter to search"), 
    pg_connection: Any = Depends(get_pg_connection),
) -> dict[str, Any]:
    pg_connection.autocommit = True # program dies here when max_lifetime is hit
    # etc etc
```

**Comment by dvarrazzo** [comment]
What database server are you using? I guess it's not normal prostgres.

The pool doesn't close connections actively which then will proceed to serve to the caller: if it closes a connection because max life has expired it will replace it with a new one. So it must be the server that closes the connection: postgres might do it because of an `idle_session_timeout` or, of course, it might be a network problem (but in your case it seems to happen regularly).

You can use the pool [`check` parameter](https://www.psycopg.org/psycopg3/docs/advanced/pool.html#connection-quality) to ask the pool to verify if a connection is still good. Try to add `check=ConnectionPool.check_connection` to your pool options.

**Comment by A-Posthuman** [comment]
I'm using the latest postgres 16.2, pretty fresh install and not many changes to the default config on it. Nothing about closing idle connections or anything I can think of that would close connections. Also I enabled the various tcp keepalives on it just in case while trying to debug this issue, but they had no effect.

Also I've verified that by changing the max_lifespan time on the pool that this is in fact the issue. When it is left to the default 3600 seconds, my program starts to fail at exactly then. If I change it to 60 seconds, my program starts to get handed closed connections from the pool after 60 seconds. So it definitely seems to be something wrong with the pool?

I have experimented with the check option before opening this issue and wasn't able to resolve the problem. The connections seem to pass through the check, but then when the rest of my program code tries to use the connection it hits the connection is closed exception.

**Comment by dvarrazzo** [comment]
This seems very surprising, it would be an error caught by a large number of users, including myself, as I have several fastapi applications deployed using the connection pool. It would also fail to pass several tests.

One thing I see that seems dodgy in your code is:

```python
def get_pg_connection(request: Request) -> Any:
    with app.state.pg_pool.connection() as conn:
        # to test if connection works, do a SELECT 1
        with conn.transaction():
            cursor = conn.cursor()
            cursor.execute("SELECT 1")
            return conn
```

if you do this, on return, the block will exit, therefore you will return the connection to the pool, and a concurrent operation might use it concurrently. So maybe here you want to use `yield conn` instead?

I think that you have this problem, and, on top of that, some part of your code is closing your connections. The pool has a guard so that, if you return a closed connection to the pool, it will generate a new one. However, because of the above, you might be closing the connection while it is in the pool.

**Comment by dvarrazzo** [comment]
It's also confusing that you set autocommit in a view: that setting will affect whatever user of the pool will pick that connection. I think you should decide upfront if you want to use autocommit or non-autcommit connection in your program and set that state as part of the configuration.

Anyway, if you want, please share a complete file/project exhibiting the problem and I can try to take a look.

**Comment by A-Posthuman** [comment]
Ok good news, your advice to change the return conn to yield conn seems to have solved the issue. Also I agree with your advice to move the autocommit up into the configuration.

I'm still not clear on why this made the max_lifetime malfunction, as I was not closing the connection in any of my program code, and also wasn't making any concurrent requests to this api since my app currently is in dev mode and I'm only manually doing 1 request at a time. Somehow max_lifetime was not creating new connections to replace the ones it closed.

But thanks for the help in resolving it!

**Comment by dvarrazzo** [comment]
No idea, curious indeed.

Good luck with Psycopg and FastAPI! FYI, a FastAPI project has been one of the test benchs for psycopg design, many features of the pool have been inspired to the need for the two to collaborate well. So hopefully you should find no problem impossible to solve :)
