### ISSUE TITLE
malloc: double free for ptr 0x1243fd200

### ISSUE THREAD

**Issue by DSLituiev** [psycopg/psycopg#823]
I am trying to run `psycopg2.connect` in Python 3.10.14 on Mac M1 and getting an error:
 
```
python(46885,0x203d8fac0) malloc: double free for ptr 0x1243fd200
python(46885,0x203d8fac0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by dvarrazzo** [comment]
Did you upgrade the system recently and have a mix of new and old libraries?

Can we have more information? Such as:

- are you using the `binary` or `c` extension? What does `psycopg.pq.__impl__` say?
- are you connecting using ldap or other authentication systems
- are you using an encrypted connection? What happens if you disable encryption?
- can you connect using psql and using _exactly the same connection string_?
- can you create a core dump and check where the crash happened?

**Comment by dvarrazzo** [comment]
I just saw https://github.com/psycopg/psycopg2/issues/1697. Is the crash you report related to psycopg 2 or 3?

**Comment by dvarrazzo** [comment]
Ah, it's psycopg2. We can close this.
