### ISSUE TITLE
The _query attribute

### ISSUE THREAD

**Issue by LongBeachHXC** [psycopg/psycopg#86]
I was leveraging the `cur.query` and `cur.params` attribute as a sanity check. I was doing some digging and noticed the changes to the Cursor API. I'm curious why NOT provide this information? I would love to be able to leverage this information as a sanity check to make sure the correct statement is being generated and being sent down the pipe.

I may be missing something obvious here but I couldn't find the equivalent as it is. I shifted to use the `cur.statusmessage` but it doesn't give me the level of granularity that I would like to see.

**Comment by dvarrazzo** [comment]
`query` and `params` are incomplete informations: you would also need at least `types`, `formats` to reconstruct what's really passed to the server. So we expose the whole `PostgresQuery` object responsible of the transformation of the Python query/params into Postgres format, instead of bloating the Cursor interface adding all the details.

However the query object is still an internal object and I prefer to not commit altogether to its interface: if there are valid reasons it might change in the future. Possible reasons might be 1) performance and 2) make it an abstract interface and provide different implementations, such as a client-side binding query too, to give an option to users finding server-side binding problematic for their use cases.

For this reason the object is only expose using a `_query` private-ish name. The object is still accessible for debug and exploration reasons (and care has been taken in order to make it available when needed, e.g. including on error and after the cursor is closed), but I'd rather discourage people from building entire services on top of it, before maybe having a chat and designing a more stable interface.

Does it make sense? What is your use case?
