### ISSUE TITLE
Documentation and/or type hints mix up Composable/Composed?

### ISSUE THREAD

**Issue by hynek** [psycopg/psycopg#862]
Hi,

the type hints for `Query` that is accepted by `Cursor.execute()` says:
https://github.com/psycopg/psycopg/blob/74e24a0396fd63096b9423e7a6278c59f0875d24/psycopg/psycopg/abc.py#L30

(I.e. `"sql.Composed"`)

While the docstring of Composable says:

https://github.com/psycopg/psycopg/blob/74e24a0396fd63096b9423e7a6278c59f0875d24/psycopg/psycopg/sql.py#L42-L44

Given the documentation and since I can't make it pass type-check, I _think_ the the type hint is wrong and it should by `"sql.Composable"`?

---

As a side-note, I got on this composable side-quest, because I couldn't pass `str`s into execute  on Pyright (and only Pyright) anymore – I suspect that's wrong too? 😅

```
error: Argument of type "str" cannot be assigned to parameter "query" of type "Query" in function "execute"
    Type "str" is incompatible with type "Query"
      "str" is incompatible with "LiteralString"
      "str" is incompatible with "bytes"
      "str" is incompatible with "SQL"
      "str" is incompatible with "Composed"
```

**Comment by dvarrazzo** [comment]
Yes, you are right: you can pass a query a `SQL` (a constant) or a `Composed` (a mix of constants, identifiers, parameters...) but you can't pass a query `Composible` subclasses such as `Identifier` or `Placeholder` because they wouldn't make sense as a complete query. So yes, I'll fix the docs.

`execute()` is annotated to take a LiteralString, which means a `str` that comes from a constant, not from a string operation. That's because, most of the times, a string operation is `"INSERT INTO ... ('%s')" % my_string` or something else unsafe. So the idea is to use the `psycopg.sql` objects for string composition and plain strings only when there is no composition going on. What type of operation is Pyright flagging you?

**Comment by hynek** [comment]
Right thanks! I was doing some benign formatting (`BEGIN TRANSACTION {isolation_level}` where `isolation_level` was/is hard-coded to `ISOLATION LEVEL READ COMMITTED` and `READ ONLY`).

**Comment by dvarrazzo** [comment]
Ok, that's easy to convert to composition of `sql.SQL` objects then.

Out of curiosity, any reason not to use the builtin [transaction control](https://www.psycopg.org/psycopg3/docs/basic/transactions.html#transaction-characteristics) methods?

**Comment by hynek** [comment]
Oof, this is a bigger topic of an internal package that I'm very excited about, but I'm afraid the world is not ready for. If by any chance you'll come to Prague next week for EP, I'll happily show you much more, but in a nutshell:

I have to use multiple databases (mostly Postgres & SQLAnywhere [yes, really :(]) both raw and via SQLAlchemy. Over the years I've learned (the hard way) that being _explicit_ about transactions is very good, actually.

I _think_ to remember that psycopg's transaction management has implicit commits which is something that I emphatically don't want. I want implicit rollbacks (learned about it in https://www.cosmicpython.com).

I think that's the answer to your question, but let me elaborate a bit more, since I suspect you might be one of the ~five people world-wide who might have a bit understanding/empathy for what I'm doing.

---

I also don't like ORMs, but I like repositories that use vanilla classes and the unit of work pattern as it is presented in the book, which mostly means a class with all the repositories in it. After implementing that pattern ten times and after SQLAlchemy started enforcing auto-begins, I've come to the conclusion that a) I don't want to implement it the 11th time and b) the repositories should only be available after I've explicitly started a transaction.

Long story short, my package is named `txmgr` and the code for using it looks something like this (this is SQLAlchemy code because I have it handy, but it's not much different with psycopg):

```python
from typing import TypeAlias

import attrs

from sqlalchemy import Connection, create_engine
from txmgr import AbstractUnitOfWork, SQLAlchemyPsycopgTransactionManager
from txmgr.typing import TxControl, TransactionManager


@attrs.define
class SomeObject:
    """
    An object with elided fields that's loaded/stored using a repo,
    but that doesn't know about databases at all.
    """

@attrs.define
class SomeObjectRepository:
    # In SQLAlchemy, a Connection is also a Cursor.
    # This is not true when using raw psycopg or raw sqlanydb.
    cursor: Connection

    def get(self, id: int) -> SomeObject:
        ...

    def add(self, ...) -> None:
        ...

# Now define the unit of work

@attrs.define
class UnitOfWork(AbstractUnitOfWork[Connection]):
    some_objects: SomeObjectRepository

    @classmethod
    def from_connection_and_cursor(
        cls, tx_control: TxControl, is_read_only: bool, cursor: Connection
    ) -> Self:
        # tx_control is the connection that does commit/rollback.
        # These methods live on AbstractUnitOfWork. Both tx_control and is_read_only
        # are defined there tool. `from_connection_and_cursor` is what gets called
        # by txmgr when the user begins a transaction.
        return cls(tx_control, is_read_only, SomeObjectRepository(cursor))


# For typing + nicer names.
MyTransactionManager: TypeAlias = TransactionManager[
    Connection, UnitOfWork
]
```

One you've got it set up like this, you can use it like this in your code:

```python
def do_things(txm: MyTransactionManager) -> None:
    # begin_read_only() instantiates the uow – it's impossible to do anything
    # before calling it
    with txm.begin_read_only() as uow:
        # Type checker knows that uow is of type UnitOfWork, declared above!
        obj = uow.some_objects.get(42)
        ...

    # same here. no more accidental auto begins; type-safe top to bottom.
    with txm.begin() as uow:
        uow.some_objects.add(...)

        uow.commit()  # necessary; auto-rollback otherwise


engine = create_engine(...)

with engine.connect() as conn:
    do_things(SQLAlchemyPsycopgTransactionManager(conn, UnitOfWork))

engine.dispose()
```

I realize many would find this over engineered, but I can't express how simpler and more understandable it made my code bases (together with [_svcs_](https://svcs.hynek.me/en/stable/)).

**Comment by dvarrazzo** [comment]
Hi, thank you for the detailed explanation and the deep thought points.

I have read [the reasoning behind explicit commits](https://www.cosmicpython.com/book/chapter_06_uow.html#_explicit_versus_implicit_commits). It doesn't convince me, as I think that the user has been explicit enough in their intentions by using the UoW block, and that rolling back is a rarity: the common behaviour for me is that, if I write certain statements in the code base, in the largest number of cases I did it because I want them to have an effect on the system. However, we are in the realm of the design opinions, and the ones of the author and yours are perfectly valid. As the author puts it, theirs is a judgement call.

Anyway, yes: psycopg implements a `transaction()` block which has its own policies: it does some composition like yours to establish the type of BEGIN the query needs, and it commits by default on block exit. As you are implementing your own, different, transaction policy, it makes sense that you will need to write the type of queries you showed above.

Unfortunately, I have other plans and I can't be in Prague next week. I hope we'll stumble into each other some other times though. Happy hacking!

**Comment by hynek** [comment]
Sure, I'm not trying to convince anyone about it and I was skeptical about it at first too. I've just started to increasingly appreciate being explicit about side-effects. I like looking at business code and knowing: OK, the data is written here, I don't have to reason about the transaction and its semantics within the package/framework anymore. It also wildly depends on what kind of software one is writing.
