### ISSUE TITLE
Use the libpq from EDB on Windows

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg#916]
We are currently building windows package using [Postgres 14](https://github.com/psycopg/psycopg/blob/af5bfa0ec2690571033e38205a98cfc8c6287134/.github/workflows/packages-bin.yml#L238-L243) because this is what is [in the runner](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#postgresql).

However [we try](https://github.com/psycopg/psycopg/blob/af5bfa0ec2690571033e38205a98cfc8c6287134/.github/workflows/packages-bin.yml#L231) to install a newer version, using [wheel_win32_before_build.bat](https://github.com/psycopg/psycopg/blob/af5bfa0ec2690571033e38205a98cfc8c6287134/tools/build/wheel_win32_before_build.bat). Either that doesn't work, or the libpq ends up in mysterious places and we can't find it.

Looking better at what choco does, it seems that it installs a package using [these instructions](https://github.com/majkinetor/au-packages/blob/master/postgresql/tools/chocolateyInstall.ps1), which is pretty much taking it from EDB website. So we can instead try to do the same and figure out where things end up.

@kemosh might be able to help?

Related:

- #852
- #912

**Comment by allaboutmikey** [comment]
Is part of the problem that `packages-bin.yml` has a hardcoded path to PG version 14?
`PATH="C:\\Program Files\\PostgreSQL\\14\\bin;$PATH"`

**Comment by allaboutmikey** [comment]
I had a look at `wheel_win32_before_build.bat` and decided to try v16 because that had the feature that originally tipped me off about the binary mismatch (in #912).
(I don't know enough to run the psycopg packaging build on my windows, so I was just doing some things manually to see where the dlls landed.)
The command `choco install postgresql16` successfully installed a postgresql server and assorted binaries/libraries in `C:\Program Files\PostgreSQL\16\`, with libpq.dll in the lib subfolder as expected.
I tested the pure python psycopg driver at this point and it successfully found the dll! 
```
Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg
>>> psycopg.pq.version()
160004
>>> exit()
```
This was in a fresh venv, with a newly installed version of python (old 3.8 uninstalled, 3.12 installed).
I then decided to install the binary package. This gives the expected version 140012 of the currently linked binary, so I pip uninstalled psycopg and reinstalled the pure python version. It still showed 140012! 
I went into the venv and the `site-packages` folder still had traces of the binary version. This is despite the pip uninstall telling me:
```
>pip uninstall psycopg[binary]
Uninstalling psycopg-3.2.2:
  Would remove:
    c:\users\mike\pypg\venv\lib\site-packages\psycopg-3.2.2.dist-info\*
    c:\users\mike\pypg\venv\lib\site-packages\psycopg\*
Proceed (Y/n)? y
  Successfully uninstalled psycopg-3.2.2
```
Seems it isn't a complete uninstall.
I pip uninstalled psycopg again, to be sure, and manually removed any psycopg related folders in the venv. Reinstalling the pure python version of psycopg now results in finding the current libpq.dll again:
```
Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg
>>> psycopg.pq.version()
160004
>>> exit()
```
All this leads me to believe that my original problem might be related to a polluted venv from an incomplete uninstall of the binary package? I'm not sure how much this relates to your building issues, but I hope it might shed some light.

**Comment by dvarrazzo** [comment]
@allaboutmikey I have done some work to install the EDB package and try to build using it in #920, but it's not currently working.

In some local tests yesterday we used the command:

```
postgresql-17.0-1-windows-x64.exe --mode unattended --enable-components commandlinetools --disable-components server,pgAdmin,stackbuilder --extract-only 1 --prefix d:\postgres
```

to perform an unattended installation of the EDB postgres distribution, but on gitlab it doesn't seem to work.

**Comment by trim21** [comment]
another option maybe, we can use vcpkg to install libpq on windows:

a working example:
```$
vcpkg install libpq:x64-windows
```

then patch current setup.py:

```diff
diff --git a/psycopg_c/setup.py b/psycopg_c/setup.py
index eeea1c94..a519cfe0 100644
--- a/psycopg_c/setup.py
+++ b/psycopg_c/setup.py
@@ -6,6 +6,7 @@ PostgreSQL database adapter for Python - optimisation package
 # Copyright (C) 2020 The Psycopg Team
 
 import os
+import pathlib
 import sys
 import subprocess as sp
 
@@ -21,6 +22,20 @@ if os.path.abspath(os.getcwd()) != here:
 
 
 def get_config(what: str) -> str:
+    if sys.platform == "win32":
+        if "VCPKG_ROOT" in os.environ:
+            print("try vcpkg", os.environ["VCPKG_ROOT"])
+            vcpkg_platform_root = pathlib.Path(
+                os.environ["VCPKG_ROOT"], "installed/x64-windows"
+            ).resolve()
+            if vcpkg_platform_root.exists():
+                if what == "libdir":
+                    if vcpkg_platform_root.joinpath('lib/libpq.lib').exists()
+                        return str(vcpkg_platform_root.joinpath("lib"))
+                if what == "includedir":
+                    if vcpkg_platform_root.joinpath('include/libpq').exists()
+                        return str(vcpkg_platform_root.joinpath("include"))
+
     pg_config = "pg_config"
     try:
         out = sp.run([pg_config, f"--{what}"], stdout=sp.PIPE, check=True)
```

**Comment by dvarrazzo** [comment]
Hello @trim21 

I didn't know about `vcpkg`, and it's disappointing that they don't package `pg_config`. Maybe what I would do, instead of this change, is to create a stub `pg_config.exe` returning the answers requested.

However, I don't know what oversight this package manager has, and I don't know if this opens us to supply chain attacks.

I will try and see if I can figure that out. The optimal, however, would be to build openssl+libpq from source.

**Comment by dvarrazzo** [comment]
It seems that vcpkg is safe to use as it's a Microsoft service.

**Comment by dvarrazzo** [comment]
(Still, the most recent package is 16.04, so it doesn't solve the problem of being outdated).

**Comment by dvarrazzo** [comment]
Closing as overtaken by #966.
