### ISSUE TITLE
Migration guide for psycopg2 to psycopg3?

### ISSUE THREAD

**Issue by cjw296** [psycopg/psycopg#934]
Apologies if I've missed it, but where can I find a migration guide for pyscopg2 to psycopg3?

I'm currently wondering what the correct way is to change code that uses `psycopg2.extras.DateTimeRange`.

https://www.psycopg.org/psycopg3/docs/basic/pgtypes.html#range-adaptation doesn't appear to cover dates and times...

**Comment by dvarrazzo** [comment]
There are a few notes [in the documentation](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html). They might miss some details but they cover most of the expected changes.

In your case I think you can just use the `Range()` you linked, because it is a generic object and it can support datetime objects.

**Comment by cjw296** [comment]
Yeah, I guess it's not super clear from the `Range` docs (or tests) that it's intended use is `Range[datetime]` instead of `DateTimeRange`, and whether that `datetime` should be the stdlib one or the one from SQLAlchemy, for example.
