### ISSUE TITLE
Row factory for returning tuples of typed classes

### ISSUE THREAD

**Issue by benjamingorman** [psycopg/psycopg#937]
[Row factories ](https://www.psycopg.org/psycopg3/docs/advanced/rows.html#row-factories) offer the very useful `class_row` option for returning a typed class instance from a cursor.

(from the docs)
```
from dataclasses import dataclass

@dataclass
class Person:
    name: str
    age: int
    weight: Optional[int] = None

from psycopg.rows import class_row
cur = conn.cursor(row_factory=class_row(Person))
cur.execute("select 'John Doe' as name, 33 as age").fetchone()
Person(name='John Doe', age=33, weight=None)
```

However what if the query is a JOIN that associates two tables?

Then we need to be able to return tuples of multiple class instances from the cursor.

e.g.
```
from dataclasses import dataclass

@dataclass
class Person:
    id: int
    name: str
    age: int
    weight: Optional[int] = None
    
@dataclass
class Pet:
  person_id: int
  id: int

from psycopg.rows import class_row
cur = conn.cursor(row_factory=class_row(Person, Pet))
cur.execute("SELECT person.*, pet.* FROM person INNER JOIN pet ON pet.person_id = person.id ").fetchall()
```

It would be very convenient if `class_row` _just worked_ in such scenarios, so that the result would be a list of tuples containing class instances.
Could this feasibly be made into a feature?
Or is there another convenient way to accomplish the same thing?

I suppose a custom row factory is one viable solution here. But this seems like a common enough use case to want to support it out of the box.

**Comment by dvarrazzo** [comment]
It is very unlikely that this can become a feature, because `person.*, pet.*` is very unlikely that can work. If both tables have `id` then it's also sort of ambiguous - it works for positional arguments but not for keyword arguments - and its brittle because adding a column to a table but not to the dataclass will break the code in a bad way.

Because you are relying on passing arguments positionally you can easy create a function `person_and_pet(data: tuple[Any, ...]) -> tuple[Person, Pet]:` and pass it to `rows.args_row`.
