### ISSUE TITLE
String-based MAC Address Queries Raise Conversion Errors in Psycopg3

### ISSUE THREAD

**Issue by yoch** [psycopg/psycopg#949]
In migrating from `psycopg2` to `psycopg3`, I've encountered a compatibility issue when querying PostgreSQL MAC address fields (`macaddr` type) using strings. Previously, with `psycopg2` and other PostgreSQL clients, string representations of MAC addresses could be used directly in queries. However, in `psycopg3`, attempting this now raises an error:

```
operator does not exist: macaddr = character varying
```

Is this lack of implicit conversion intended, or is there a recommended workaround for maintaining compatibility with existing code?

Thank you!

**Comment by dvarrazzo** [comment]
I don't think this is the case, no:

```python
>>> import psycopg
>>> conn = psycopg.connect(autocommit=True)
>>> conn.execute("create table test_macaddr (id serial primary key, macaddr macaddr)")
>>> conn.execute("insert into test_macaddr(macaddr) values ('08:00:2b:01:02:03')")
>>> conn.execute("select * from test_macaddr where macaddr = %s", ("08:00:2b:01:02:03",)).fetchone()
(1, '08:00:2b:01:02:03')
```

In psycopg 3 python strings are passed to postgres using the unknown oid, exactly to avoid the problem you report. You seem to be using a non-standard adapters mapping.

In order to work around the problem you can probably use an explicit cast, such as `where macaddr = %s::macaddr`.

**Comment by yoch** [comment]
I think you right, it seem to be a SQLAlchemy issue : https://github.com/sqlalchemy/sqlalchemy/issues/12060
