### ISSUE TITLE
psycopg-binary should require a compatible version of psycopg

### ISSUE THREAD

**Issue by CaselIT** [psycopg/psycopg#964]
Hi,

I ended up with the following config locally that caused issues:
```
psycopg                       3.1.7
psycopg-binary                3.2.3
```

That caused issues like:
```py
import psycopg
from psycopg import types

with psycopg.connect(
    "postgresql://scott:tiger@127.0.0.1:5432/test",
    cursor_factory=psycopg.ClientCursor,
) as c:
    print(types.TypeInfo.fetch(c, "int"))
```
this outputs:
```
Traceback (most recent call last):
  File "path\to\test1.py", line 10, in <module>
    print(types.TypeInfo.fetch(c, "int"))
          ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "path\to\Lib\site-packages\psycopg\_typeinfo.py", line 93, in fetch
    cur.execute(cls._get_info_query(conn), {"name": name})
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path\to\Lib\site-packages\psycopg\cursor.py", line 728, in execute
    raise ex.with_traceback(None)
psycopg.NotSupportedError: client-side cursors don't support binary results
```

Updating `psycopg` to the same version of the binary package fixed that issue.

Personally I find it very strange that `psycopg-binary` doesn't require any version of `psycopg`, since that seems required. Without it I get `AttributeError: module 'psycopg' has no attribute 'connect'`.

What's the rationale of not requiring it?

**Comment by dvarrazzo** [comment]
The versions of psycopg and psycopg binary are [interlocked 1:1](https://github.com/psycopg/psycopg/blob/c7b8ed5d85e15874eb4dc71d29c1b08800bf9606/psycopg/setup.cfg#L66) at metadata level. This means that if you install the library the way expected, with `pip install psycopg[binary]`, you are guaranteed to get compatible packages.

I don't want to lock the libraries at code level, for example checking a perfect version match at import time, because sometimes, maybe for debug, maybe for reasons external to what we can do, we need to allow some flexibility. It happened in the past, where we didn't have any available builder to create new binary packages and we needed to release a python-only bugfix, therefore we had a Python version installing a one-version-older binary. In that case we just had to fudge the packages metadata; adding a lock on import it would complicate the matter even more.

Personally, at development time, this check would drive me crazy. Any insignificant bump of the python metadata would require to recompile the C library, switching branches would be a mess... I would definitely hate a strict version check with passion.

> Personally I find it very strange that psycopg-binary doesn't require any version of psycopg, since that seems required

psycopg-binary is an internal module, which doesn't have an interface of its own. The interface of the dependency is on the opposite side: `psycopg` requires `psycopg-binary` (if the `binary` extra is selected). I seem to remember that, in the past, we even tried to include this dependency, and for some reason we had to drop it. Probably the dependency loop was making pip unhappy. For sure it would be a further problem in the use case stated earlier, to allow a certain controlled version slippage to deliver a Python-only bugfix.

Honestly we cannot restrain all the possible ways someone can mess up with their Python environment: this is not our responsibility. You seem to have upgraded psycopg-binary without upgrading psycopg: this is not a documented or supported upgrade path.

**Comment by CaselIT** [comment]
Ok. would an opposite dependency work?
something like `psycopg-binary` requies `psycopg` >= it's own version? Or maybe `~` to the minor version (so 3.2 requires a 3.2.x of the other)?

> this is not a documented or supported upgrade path.

not sure if it's wort it, but maybe this is a good place for a warning?

**Comment by dvarrazzo** [comment]
> Ok. would an opposite dependency work?
> something like psycopg-binary requies psycopg >= it's own version? Or maybe ~ to the minor version (so 3.2 requires a 3.2.x of the other)?

What is the use case here?

**Comment by CaselIT** [comment]
avoiding having a broken install without any other obvious sign of one.

I guess what I'm looking for are "peer dependencies" that aren't a thing in python. https://nodejs.org/en/blog/npm/peer-dependencies
