### ISSUE TITLE
start  transaction from connection pool with isolation level and read_only?

### ISSUE THREAD

**Issue by trim21** [psycopg/psycopg#965]
Hi, thanks for your works on this package.

I'm using a connection pool with normally Read Committed isolation level, but in some case I need a `SERIALIZABLE` and read only transaction. 

Is it possible to do something like this without changing default isolcation level of connection?

```python
with self.db.connection() as conn:
    with conn.transaction(isolation_level=IsolationLevel.SERIALIZABLE):
        ...

with self.db.connection() as conn:
    with conn.transaction(read_only=True):
        ...
```

**Comment by dvarrazzo** [comment]
Not currently, no. I have a short answer for you, to solve your problem, and a long answer that is about implementing such feature.

For you: assuming that you are not using nested transactions, and you are just interested to make sure that a connection is not returned in the pool in an unwelcome state, you can just execute:

```python
with self.db.connection() as conn:
    with conn.transaction():
        conn.execute("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE")
```

at the end of the transaction, either on COMMIT or ROLLBACK, the server would reset the isolation level to the default.

---

This concludes our TED talk. Thank you for joining us. Nothing to see here. Move along.

... still here? oh, well... :eyes: 

---

What about implementing `conn.transaction(**characteristics)`?

It does seem a good idea, but it would conflict with nested transaction, because you can `BEGIN ISOLATION LEVEL SERIALIZABLE` but, in order to support:

```python
with self.db.connection() as conn:
    with conn.transaction() as t1:  # BEGIN
        with conn.transaction(isolation_level=IsolationLevel.SERIALIZABLE) as t2:  # SAVEPOINT
```

we should manage resetting the connection to whatever state it was upon `ROLLBACK TO SAVEPOINT` and `RELEASE SAVEPOINT` at the end of the block. So for example:

```python
with self.db.connection() as conn:
    with conn.transaction(read_only=True) as t1:
        with conn.transaction(isolation_level=IsolationLevel.SERIALIZABLE, read_only=False) as t2:
```
would require statements:
```
# upon entering t1
BEGIN TRANSACTION READ ONLY; 

# upon entering t2
SAVEPOINT s1
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

# upon leaving t2
RELEASE SAVEPOINT s1
SET TRANSACTION ISOLATION LEVEL READ ONLY;
RESET transaction_isolation;  # there is no way to reset a state via `SET TRANSACTION` I think

# upon leaving t1
COMMIT
```

(in alternative `SET LOCAL transaction_*` would be probably better than `SET TRANSACTION` in order to allow a reset to default).

So there would be some bookkeeping to do in order to record what settings were done on the stack and to be sure that leaving any nested transaction would restore these settings. By looking at [the docs](https://www.postgresql.org/docs/current/sql-set.html) it seems like `ROLLBACK TO SAVEPOINT` reset a `SET LOCAL` issued after saving, but `RELEASE` doesn't, so I think that such bookkeeping would be necessary.

**Comment by trim21** [comment]
I'm not in a nest transaction, this short answer looks perfect to me.

**Comment by trim21** [comment]
Not sure should I close this issue or not?

**Comment by dvarrazzo** [comment]
> Not sure should I close this issue or not?

Leave it to me. I'll close this but I will open an "improvement" ticket to leave the idea of the `transaction()` parameters around.

**Comment by dvarrazzo** [comment]
Idea persisted in #970.
