### ISSUE TITLE
Drop Python 3.8 compatibility

### ISSUE THREAD

**Issue by pauloxnet** [psycopg/psycopg#976]
Python 3.8 is EOL since 2024-10-07 so I think it would be safe to drop the support for this unmaintained version of Python

**Comment by dvarrazzo** [comment]
Yes, that's true, and it will surely happen.

Usually we drop compatibility on minor releases: as soon as we have a new feature (let's say #932) we would fork `maint-3.2` from `master`. We would then keep `maint-3.2` as bugfix and we would proceed to drop Python 3.8 compatibility from master, which eventually would be released as Psycopg 3.3.

**Comment by stankudrow** [comment]
Can it be split into minor independent PRs like "Drop Py3.8 for psycopg_pool" and so on without links to any features?

**Comment by dvarrazzo** [comment]
@stankudrow It can be done any moment, when it will be done it will be separated from the 3.2 maintenance branch. It doesn't need to be "linked to a feature", maybe I didn't explain myself clearly.

If we do it now, and there is no difference between master and Python 3.2, no new feature, then it's a waste of effort to maintain two otherwise identical branches; as we need to cherry-pick changes and keep the two branches in parallel, at least for bugfux-related changes, so I'd rather delay this moment until needed.

By the way I am considering that the refactoring in #974 is a bit too invasive for the next 3.2.x so maybe we can create masint-3.2 soon and land that on master instead.

As to implement it in several MR, sure, it can be done, but I don't think it's so much work that is necessary. I would drop 3.8 from metadata first, then from the CI, then I would grep around the code looking for `3.?8`, `3.?9` etc and kill dead code branches, dead requirements, etc.

**Comment by stankudrow** [comment]
> @stankudrow It can be done any moment, when it will be done it will be separated from the 3.2 maintenance branch. It doesn't need to be "linked to a feature", maybe I didn't explain myself clearly.
> 
> If we do it now, and there is no difference between master and Python 3.2, no new feature, then it's a waste of effort to maintain two otherwise identical branches; as we need to cherry-pick changes and keep the two branches in parallel, at least for bugfux-related changes, so I'd rather delay this moment until needed.
> 
> By the way I am considering that the refactoring in #974 is a bit too invasive for the next 3.2.x so maybe we can create masint-3.2 soon and land that on master instead.
> 
> As to implement it in several MR, sure, it can be done, but I don't think it's so much work that is necessary. I would drop 3.8 from metadata first, then from the CI, then I would grep around the code looking for `3.?8`, `3.?9` etc and kill dead code branches, dead requirements, etc.

I would love to take part in dropping Python 3.8 support and the reason to have a PR touching only, shall we say, `psycopg_pool` is making progress in smaller steps. I can open such a PR unless someone has done it already.

**Comment by dvarrazzo** [comment]
Done: I have created a maint-3.2 branch for bugfix only and we are now free to deprecate Python 3.8 in master.

If you would like to contribute some changeset feel free to do so, @stankudrow, and thank you very much for your help!

**Comment by pauloxnet** [comment]
Thanks, @stankudrow and @dvarrazzo to fix this issue so fast. :+1:

**Comment by dvarrazzo** [comment]
Ok to merge #982 in its current state?
